export function GuardianReferenceNotice() {
  return (
    <section className="portal-panel" aria-label="Guardian automatic reference numbering">
      <div className="portal-panel-heading">
        <div>
          <p>System reference</p>
          <h2>Guardian reference numbers are assigned automatically</h2>
        </div>
        <span>LSCSO-GDN-YYYY-####</span>
      </div>
      <p>
        The permanent Guardian reference is generated by the system when the record is first saved. The separate related event/reference field remains available for CAD, case, incident, or training IDs.
      </p>
    </section>
  );
}
