"use client";

import Link from "next/link";
import { useEffect, useMemo, useRef, useState } from "react";

type DirectoryMember = { personnelId:string;displayName:string;rank:string;callSign:string|null;division:string;status:string;probationary:boolean;probationEndsAt:string|null;probationDaysRemaining:number|null };
type PersonnelDirectoryProps = { personnel: DirectoryMember[] };
const RECENT_KEY="lscso.command.recent-personnel:v1";const FAVORITES_KEY="lscso.command.favorite-personnel:v1";
function probationSummary(member:DirectoryMember){return member.probationary&&member.probationDaysRemaining?`Probation · ${member.probationDaysRemaining}d remaining`:null}

export function PersonnelDirectory({personnel}:PersonnelDirectoryProps){
  const[query,setQuery]=useState("");const[division,setDivision]=useState("");const[rank,setRank]=useState("");const[status,setStatus]=useState("");const[probationOnly,setProbationOnly]=useState(false);const[recentIds,setRecentIds]=useState<string[]>([]);const[favoriteIds,setFavoriteIds]=useState<string[]>([]);const resultsRef=useRef<HTMLDivElement>(null);
  useEffect(()=>{try{const stored=JSON.parse(localStorage.getItem(RECENT_KEY)??"[]");if(Array.isArray(stored))setRecentIds(stored.filter((item)=>typeof item==="string").slice(0,6));const favorites=JSON.parse(localStorage.getItem(FAVORITES_KEY)??"[]");if(Array.isArray(favorites))setFavoriteIds(favorites.filter((item)=>typeof item==="string").slice(0,12))}catch{setRecentIds([]);setFavoriteIds([])}},[]);
  const recent=useMemo(()=>recentIds.map((id)=>personnel.find((member)=>member.personnelId===id)).filter(Boolean) as DirectoryMember[],[personnel,recentIds]);
  const favorites=useMemo(()=>favoriteIds.map((id)=>personnel.find((member)=>member.personnelId===id)).filter(Boolean) as DirectoryMember[],[favoriteIds,personnel]);
  const divisions=useMemo(()=>Array.from(new Set(personnel.map((member)=>member.division||"Unassigned"))).sort(),[personnel]);
  const ranks=useMemo(()=>Array.from(new Set(personnel.map((member)=>member.rank))).sort(),[personnel]);
  const statuses=useMemo(()=>Array.from(new Set(personnel.map((member)=>member.status))).sort(),[personnel]);
  const activeFilters=Boolean(query.trim()||division||rank||status||probationOnly);
  const filtered=useMemo(()=>{const normalized=query.trim().toLowerCase();if(!activeFilters)return[];return personnel.filter((member)=>{if(division&&member.division!==division)return false;if(rank&&member.rank!==rank)return false;if(status&&member.status!==status)return false;if(probationOnly&&!member.probationary)return false;const haystack=[member.displayName,member.personnelId,member.callSign,member.rank,member.division,member.status,member.probationary?"probation probationary":""].filter(Boolean).join(" ").toLowerCase();return !normalized||haystack.includes(normalized)})},[activeFilters,division,personnel,probationOnly,query,rank,status]);
  function remember(personnelId:string){setRecentIds((current)=>{const next=[personnelId,...current.filter((id)=>id!==personnelId)].slice(0,6);try{localStorage.setItem(RECENT_KEY,JSON.stringify(next))}catch{}return next})}
  function clearFilters(){setQuery("");setDivision("");setRank("");setStatus("");setProbationOnly(false)}
  function focusFirstResult(){window.requestAnimationFrame(()=>resultsRef.current?.querySelector<HTMLElement>("a[href]")?.focus())}

  return <div className="command-v2-directory">
    <section className="portal-panel command-v2-directory-search"><div className="portal-panel-heading"><div><p>Find personnel</p><h2>Personnel directory</h2></div>{activeFilters?<button className="portal-text-button" onClick={clearFilters} type="button">Clear all</button>:null}</div>
      <label className="command-v2-search-field"><span>Search</span><input type="search" value={query} onChange={(event)=>setQuery(event.target.value)} onKeyDown={(event)=>{if(event.key==="ArrowDown"&&filtered.length){event.preventDefault();focusFirstResult()}}} placeholder="Name, call sign, personnel ID, rank, division..."/></label>
      <div className="personnel-directory-filters">
        <label><span>Division</span><select value={division} onChange={(event)=>setDivision(event.target.value)}><option value="">All divisions</option>{divisions.map((item)=><option key={item}>{item}</option>)}</select></label>
        <label><span>Rank</span><select value={rank} onChange={(event)=>setRank(event.target.value)}><option value="">All ranks</option>{ranks.map((item)=><option key={item}>{item}</option>)}</select></label>
        <label><span>Status</span><select value={status} onChange={(event)=>setStatus(event.target.value)}><option value="">All statuses</option>{statuses.map((item)=><option key={item}>{item}</option>)}</select></label>
        <label className="personnel-directory-probation"><input checked={probationOnly} onChange={(event)=>setProbationOnly(event.target.checked)} type="checkbox"/><span>Probation only</span></label>
      </div>
    </section>

    {activeFilters?<section className="portal-panel"><div className="portal-panel-heading"><div><p>Results</p><h2>{filtered.length} found</h2></div><span>{[division,rank,status,probationOnly?"Probation":null].filter(Boolean).join(" · ")||"Search results"}</span></div><div className="command-v2-personnel-results" ref={resultsRef}>{filtered.map((member)=><Link href={`/portal/command/personnel/${member.personnelId}`} key={member.personnelId} onClick={()=>remember(member.personnelId)}><div><strong>{favoriteIds.includes(member.personnelId)?"★ ":""}{member.displayName}</strong><span>{member.rank} · {member.callSign||"No call sign"} · {member.personnelId}</span></div><div><span>{member.division}</span><span className="personnel-directory-status"><b>{member.status}</b>{member.probationary?<b title={member.probationEndsAt?`Probation ends ${new Date(member.probationEndsAt).toLocaleDateString()}`:undefined}>PROBATION · {member.probationDaysRemaining}D</b>:null}</span></div></Link>)}{!filtered.length?<div className="portal-empty-state"><strong>No personnel match the current filters.</strong><span>Clear one or more filters to broaden the directory.</span></div>:null}</div></section>:null}

    <div className="command-v2-workspace-grid command-v2-directory-lower"><section className="portal-panel command-v2-launcher"><div className="portal-panel-heading"><div><p>Priority access</p><h2>Pinned personnel</h2></div></div>{favorites.length?<div className="command-v2-mini-list">{favorites.map((member)=><Link href={`/portal/command/personnel/${member.personnelId}`} key={member.personnelId} onClick={()=>remember(member.personnelId)}><strong>★ {member.displayName}</strong><span>{member.rank} · {member.callSign||member.personnelId}{probationSummary(member)?` · ${probationSummary(member)}`:""}</span></Link>)}</div>:<div className="portal-empty-state"><strong>No personnel pinned yet.</strong><span>Open a personnel record and use Pin personnel for fast repeat access.</span></div>}</section><section className="portal-panel command-v2-launcher"><div className="portal-panel-heading"><div><p>Repeat access</p><h2>Recently viewed</h2></div></div>{recent.length?<div className="command-v2-mini-list">{recent.map((member)=><Link href={`/portal/command/personnel/${member.personnelId}`} key={member.personnelId} onClick={()=>remember(member.personnelId)}><strong>{member.displayName}</strong><span>{member.rank} · {member.callSign||member.personnelId}{probationSummary(member)?` · ${probationSummary(member)}`:""}</span></Link>)}</div>:<div className="portal-empty-state"><strong>No recently viewed personnel yet.</strong></div>}</section><section className="portal-panel command-v2-launcher"><div className="portal-panel-heading"><div><p>Roster access</p><h2>Department roster</h2></div></div><p className="command-v2-compact-copy">The live roster is the department-wide personnel view. The Command roster keeps internal personnel and account-status tools.</p><div className="command-v2-action-row"><a className="portal-button portal-button--secondary" href="https://lscsoroster.vercel.app" target="_blank" rel="noreferrer">Open live roster</a><Link className="portal-button portal-button--secondary" href="/portal/command/personnel/roster">Open Command roster</Link></div></section></div>
  </div>
}
