"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { applicationLabel, APPLICATION_STATUSES } from "@/lib/recruitment/application";

type Item = { id:string; applicationNumber:number; fullName:string; discord:string; status:string; submittedAt:string; updatedAt:string; reviewer:string | null; reviewerId:string | null };
export function ApplicationsDirectory({ items, reviewers }: { items: Item[]; reviewers: Array<{id:string; name:string}> }) {
  const [query, setQuery] = useState(""), [status, setStatus] = useState(""), [reviewer, setReviewer] = useState(""), [order, setOrder] = useState("newest");
  const rows = useMemo(() => items.filter((item) => (!query || `${item.fullName} ${item.discord} ${applicationLabel(item.applicationNumber)}`.toLowerCase().includes(query.toLowerCase())) && (!status || item.status === status) && (!reviewer || item.reviewerId === reviewer)).sort((a,b) => order === "newest" ? +new Date(b.submittedAt) - +new Date(a.submittedAt) : +new Date(a.submittedAt) - +new Date(b.submittedAt)), [items, query, status, reviewer, order]);
  return <section className="portal-panel recruitment-directory"><div className="recruitment-filters"><label>Search<input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Applicant or APP number" /></label><label>Status<select value={status} onChange={(e) => setStatus(e.target.value)}><option value="">All statuses</option>{APPLICATION_STATUSES.map((value) => <option key={value}>{value}</option>)}</select></label><label>Reviewer<select value={reviewer} onChange={(e) => setReviewer(e.target.value)}><option value="">All reviewers</option>{reviewers.map((person) => <option value={person.id} key={person.id}>{person.name}</option>)}</select></label><label>Sort<select value={order} onChange={(e) => setOrder(e.target.value)}><option value="newest">Newest first</option><option value="oldest">Oldest first</option></select></label></div><div className="recruitment-list" role="list">{rows.map((item) => <article key={item.id} role="listitem"><div><strong>{applicationLabel(item.applicationNumber)}</strong><span>{item.fullName} · {item.discord}</span></div><div><b className={`recruitment-status recruitment-status--${item.status.toLowerCase().replaceAll(" ", "-")}`}>{item.status}</b><span>Submitted {new Date(item.submittedAt).toLocaleDateString()}</span></div><div><span>Reviewer</span><strong>{item.reviewer ?? "Unassigned"}</strong></div><div><span>Updated</span><strong>{new Date(item.updatedAt).toLocaleDateString()}</strong></div><Link className="portal-button" href={`/portal/command/applications/${item.id}`} aria-label={`Review ${applicationLabel(item.applicationNumber)} for ${item.fullName}`}>Review</Link></article>)}{!rows.length ? <div className="portal-empty-state"><strong>No applications match these filters.</strong><span>Adjust your search or filters to see more records.</span></div> : null}</div></section>;
}
