-- LSCSO V2 PERSONNEL DOCUMENT VAULT
-- DRAFT ONLY. Do not apply until V2 authority/RLS rules are finalized.

create table public.personnel_documents (
  id uuid primary key default gen_random_uuid(),
  document_number bigint generated by default as identity unique,
  profile_id uuid not null references public.personnel_profiles(id) on delete restrict,
  title text not null check (char_length(title) between 2 and 180),
  category text not null check (category in (
    'Guardians','Evaluations','Training','Certifications','Leave / LOA',
    'Disciplinary','Administrative','Other'
  )),
  document_date date,
  source_type text not null default 'Manual' check (source_type in (
    'Manual','Guardian','Certification','Training','Leave','Personnel Action','Other'
  )),
  source_record_id text,
  visibility text not null default 'Personnel' check (visibility in (
    'Personnel','Supervisory','Command','Executive'
  )),
  status text not null default 'Active' check (status in ('Active','Archived','Removed')),
  storage_bucket text not null default 'personnel-documents',
  storage_path text not null,
  file_name text not null,
  mime_type text,
  file_size_bytes bigint check (file_size_bytes is null or file_size_bytes >= 0),
  uploaded_by uuid not null references public.personnel_profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  archived_at timestamptz,
  archived_by uuid references public.personnel_profiles(id),
  removal_reason text,
  removed_at timestamptz,
  removed_by uuid references public.personnel_profiles(id)
);

create index personnel_documents_profile_idx
  on public.personnel_documents (profile_id, document_date desc, created_at desc);

create index personnel_documents_category_idx
  on public.personnel_documents (profile_id, category, status);

create unique index personnel_documents_storage_path_unique
  on public.personnel_documents (storage_bucket, storage_path);

alter table public.personnel_documents enable row level security;

-- Storage bucket should be private. This statement is intentionally staged here
-- and must only be applied together with finalized object-level storage policies.
insert into storage.buckets (id, name, public)
values ('personnel-documents', 'personnel-documents', false)
on conflict (id) do update set public = false;

-- IMPORTANT:
-- Do not add permissive SELECT/INSERT/UPDATE/DELETE policies here.
-- Final policies must call the centralized V2 personnel authority resolver so:
--   * Sheriff / Undersheriff / Major / Captain retain authorized command reach.
--   * 1st Lieutenant and below are limited to active purview.
--   * FTO training authority does not grant general personnel-vault access.
--   * directed actions only expose records required for the directed action.
--   * recusals can remove access for the affected matter.
--   * self access is explicitly controlled by document visibility/category.
--   * storage.objects policies mirror personnel_documents access exactly.
