import type { ArchiveRecord } from "./archive-canon";

export const supplementalArchiveRecords: Record<string, ArchiveRecord[]> = {
  "mccall-bell": [
    {
      id: "north-county-wrecker-ring",
      folder: "Criminal Organizations",
      documentCode: "ORG-65-007",
      title: "North County Wrecker Ring",
      dateLabel: "1964–1967",
      release: "Partially Released",
      status: "DISBANDED",
      stamp: "PARTIAL RELEASE",
      summary: "A loose network of towing yards and repair shops tied to stolen vehicles, stripped parts, and fraudulent recovery claims.",
      body: [
        "The North County Wrecker Ring developed during the first years of LSCSO, when the county had few standardized vehicle-recovery procedures. Deputies linked several towing operators and repair yards to vehicles reported stolen in Los Santos and neighboring jurisdictions.",
        "A surviving intelligence sheet names a county employee who was interviewed but never charged. That name remains {{REDACTED}} in the public copy.",
        "The case helped drive the first standardized impound and recovered-vehicle logs used by the Sheriff’s Office.",
      ],
    },
    {
      id: "white-fence-network",
      folder: "Criminal Organizations",
      documentCode: "ORG-74-021",
      title: "White Fence Network",
      dateLabel: "1973–1976",
      release: "Public",
      status: "DISRUPTED",
      stamp: "CLOSED INVESTIGATION",
      summary: "A property-fencing network moving stolen tools, farm equipment, and household goods through swap meets and rural businesses.",
      body: [
        "The White Fence Network was less hierarchical than the Red Mesa Outfit and relied on a rotating group of buyers, resellers, and storage locations. Patrol reports from several districts were ultimately connected through serial-number comparisons and property receipts.",
        "The investigation resulted in multiple recovery warrants and became an early example of why a countywide property index mattered.",
      ],
    },
    {
      id: "operation-county-line",
      folder: "Operations",
      documentCode: "OP-CL-65",
      title: "Operation County Line",
      dateLabel: "1965–1966",
      release: "Public",
      status: "CLOSED",
      stamp: "AFTER-ACTION FILE",
      summary: "Early multi-jurisdiction vehicle-theft operation conducted during LSCSO’s first years.",
      body: [
        "Operation County Line coordinated LSCSO patrol deputies with neighboring agencies after stolen vehicles began appearing on rural county roads with altered plates and removed identification tags.",
        "The operation produced modest arrest numbers but exposed inconsistent radio terminology and unclear responsibility when a pursuit crossed jurisdictional boundaries. Bell later incorporated those lessons into field procedures and report-routing guidance.",
      ],
    },
    {
      id: "operation-white-fence",
      folder: "Operations",
      documentCode: "OP-WF-74",
      title: "Operation White Fence",
      dateLabel: "1974–1976",
      release: "Public",
      status: "CLOSED",
      stamp: "CLOSED INVESTIGATION",
      summary: "Property-recovery and fencing investigation targeting the White Fence Network.",
      body: [
        "Deputies used serial-number ledgers, controlled property markings, and coordinated warrant service to identify storage locations connected to the White Fence Network.",
        "The after-action file notes that several recoveries were delayed because victims had not recorded identifying information. McCall subsequently authorized public property-identification campaigns through county fairs and civic meetings.",
      ],
    },
    {
      id: "harmony-service-station-homicide",
      folder: "Cold Cases",
      documentCode: "CC-66-012",
      title: "Harmony Service Station Homicide",
      dateLabel: "1966",
      release: "Partially Released",
      status: "COLD",
      stamp: "COLD CASE",
      summary: "Unsolved overnight homicide at a rural service station outside Harmony.",
      body: [
        "A service-station attendant was found deceased shortly before dawn after a passerby reported the business open but unattended. Cash remained in the register, and investigators believed the motive may have involved a private dispute rather than robbery.",
        "A witness described a dark sedan leaving the area and later identified a possible driver. The surviving witness identity and portions of the identification statement remain {{REDACTED}}.",
      ],
    },
    {
      id: "zancudo-quarry-john-doe",
      folder: "Cold Cases",
      documentCode: "CC-75-048",
      title: "Zancudo Quarry John Doe",
      dateLabel: "1975",
      release: "Public",
      status: "COLD",
      stamp: "UNIDENTIFIED PERSON",
      summary: "Unidentified deceased male recovered from an abandoned quarry access road.",
      body: [
        "The decedent was located by county workers near a disused quarry approach. No identification was recovered, and fingerprint comparisons available at the time produced no match.",
        "The file contains clothing descriptions, dental notes, and a hand-drawn property inventory. Later administrations periodically re-examined the case as identification methods improved, but the individual remains unidentified in the archive record.",
      ],
    },
    {
      id: "prisoner-transport-review",
      folder: "Internal Affairs",
      documentCode: "IA-65-003",
      title: "Prisoner Transport Complaint Review",
      dateLabel: "1965–1966",
      release: "Partially Released",
      status: "CLOSED",
      stamp: "HISTORICAL REVIEW",
      summary: "Internal review of inconsistent prisoner transport, search, and transfer documentation.",
      body: [
        "The review followed several complaints about inconsistent prisoner searches and missing transfer signatures between field deputies and detention staff.",
        "No department-wide misconduct finding was sustained, but the inquiry documented gaps in training and written procedure. One personnel disposition remains {{REDACTED}}.",
        "McCall and Bell responded with standardized prisoner-handling forms and supervisor review requirements.",
      ],
    },
    {
      id: "report-alteration-inquiry",
      folder: "Internal Affairs",
      documentCode: "IA-76-014",
      title: "Report Alteration Inquiry",
      dateLabel: "1976",
      release: "Partially Released",
      status: "CLOSED",
      stamp: "REDACTIONS REMAIN",
      summary: "Inquiry into handwritten changes made to an arrest narrative after supervisor review.",
      body: [
        "A supervisor discovered material handwritten changes on a completed arrest report after the original deputy had signed it. The review found that the changes were made during an informal correction process that lacked clear documentation.",
        "The personnel finding remains partially restricted: {{REDACTED}}. The case resulted in a rule requiring material report changes to be initialed and dated by the person making them.",
      ],
    },
    {
      id: "first-recruit-school",
      folder: "Achievements",
      documentCode: "ADM-66-005",
      title: "First Department Recruit School",
      dateLabel: "1966",
      release: "Public",
      stamp: "PERMANENT RETENTION",
      summary: "The first internally organized LSCSO recruit orientation and field-preparation program.",
      body: [
        "The 1966 recruit school provided new deputies with common instruction on report writing, county geography, prisoner handling, radio procedure, and patrol expectations before field assignment.",
        "The program was modest compared with later academies, but it ended the practice of assigning newly hired deputies solely through informal on-the-job orientation.",
      ],
    },
    {
      id: "county-radio-net-expansion",
      folder: "Achievements",
      documentCode: "ADM-70-011",
      title: "County Radio Net Expansion",
      dateLabel: "1970–1972",
      release: "Public",
      stamp: "ARCHIVAL RECORD",
      summary: "Expansion of base and mobile radio coverage across rural patrol areas.",
      body: [
        "The project added repeat capability and standardized radio identifiers for units operating in remote sections of Los Santos County.",
        "Coverage remained imperfect, but command correspondence credited the expansion with reducing missed calls and improving supervisor awareness of field activity.",
      ],
    },
    {
      id: "mccall-retirement-letter",
      folder: "Correspondence",
      documentCode: "EXEC-CORR-78-031",
      title: "Sheriff McCall Retirement Letter",
      dateLabel: "June 1978",
      release: "Public",
      stamp: "EXECUTIVE FILE",
      summary: "McCall’s final department-wide letter before the 1978 transition of command.",
      body: [
        "McCall thanked personnel for building what he described as a permanent county institution from a fragmented set of responsibilities. He emphasized that written standards and public trust mattered more than any individual administration.",
        "Bell attached a short handwritten note directing that all open administrative files be inventoried before transition to Sheriff-elect Elena Vance.",
      ],
    },
  ],

  "vance-cole": [
    {
      id: "west-vine-freight-crew",
      folder: "Criminal Organizations",
      documentCode: "ORG-80-006",
      title: "West Vine Freight Crew",
      dateLabel: "1979–1983",
      release: "Public",
      status: "DISBANDED",
      stamp: "CLOSED INVESTIGATION",
      summary: "Cargo-theft crew exploiting rapidly expanding commercial districts and poorly coordinated private security.",
      body: [
        "The West Vine Freight Crew targeted small warehouses and loading yards during the county’s rapid commercial expansion. Investigators linked the group to stolen appliances, electronics, and construction materials sold through temporary businesses.",
        "The case forced patrol districts to share burglary patterns more consistently and helped justify expanded investigative briefings between shifts.",
      ],
    },
    {
      id: "paleto-card-room-network",
      folder: "Criminal Organizations",
      documentCode: "ORG-90-031",
      title: "Paleto Card Room Network",
      dateLabel: "1989–1993",
      release: "Partially Released",
      status: "DISRUPTED",
      stamp: "PARTIAL RELEASE",
      summary: "Illegal gambling and loan-sharking network operating through private clubs and back-room card games.",
      body: [
        "The network operated through several clubs and social organizations whose public-facing activities were largely legitimate. Investigators documented illegal high-stakes gambling, unlicensed lending, and intimidation tied to unpaid debts.",
        "Two confidential-source references remain {{REDACTED}} in the public copy. The organization dissolved after licensing actions and prosecutions in the early 1990s.",
      ],
    },
    {
      id: "operation-crosswind",
      folder: "Operations",
      documentCode: "OP-CW-81",
      title: "Operation Crosswind",
      dateLabel: "1981–1982",
      release: "Public",
      status: "CLOSED",
      stamp: "AFTER-ACTION FILE",
      summary: "Burglary suppression operation spanning several fast-growing patrol districts.",
      body: [
        "Operation Crosswind paired plainclothes surveillance with marked patrol saturation after a series of warehouse and construction-site burglaries.",
        "The operation produced arrests and recovered property, but its most important administrative result was a recommendation for permanent district-level supervisory coverage during overnight hours.",
      ],
    },
    {
      id: "operation-night-ledger",
      folder: "Operations",
      documentCode: "OP-NL-90",
      title: "Operation Night Ledger",
      dateLabel: "1990–1992",
      release: "Partially Released",
      status: "CLOSED",
      stamp: "PUBLIC RELEASE COPY",
      summary: "Undercover investigation into illegal gambling and coercive lending tied to the Paleto Card Room Network.",
      body: [
        "Deputies documented recurring card games, cash loans, and threats against borrowers through surveillance and undercover contacts.",
        "The final report withholds one cooperating participant and a financial attachment: {{REDACTED}}. The operation resulted in arrests, licensing referrals, and closure of several private clubs.",
      ],
    },
    {
      id: "sandy-motel-room-four",
      folder: "Cold Cases",
      documentCode: "CC-81-023",
      title: "Sandy Motel — Room Four",
      dateLabel: "1981",
      release: "Partially Released",
      status: "COLD",
      stamp: "COLD CASE",
      summary: "Unsolved death of a transient guest at a roadside motel in the eastern county.",
      body: [
        "A motel employee discovered the victim after the guest failed to check out. The room showed no clear signs of forced entry, and investigators recovered property suggesting the victim intended to continue traveling.",
        "A witness described another guest using a name later determined to be false. Portions of that statement remain {{REDACTED}} while the identification lead remains unresolved.",
      ],
    },
    {
      id: "grapeseed-produce-yard-case",
      folder: "Cold Cases",
      documentCode: "CC-92-067",
      title: "Grapeseed Produce Yard Homicide",
      dateLabel: "1992",
      release: "Public",
      status: "COLD",
      stamp: "COLD CASE",
      summary: "Unresolved homicide discovered during an overnight produce-yard delivery window.",
      body: [
        "The victim was located behind a packing facility before the morning shift arrived. Investigators identified several possible motives but could not connect physical evidence to a specific suspect.",
        "The case remains indexed for comparison against later commercial-yard robberies and violent offenses.",
      ],
    },
    {
      id: "use-of-force-reporting-review",
      folder: "Internal Affairs",
      documentCode: "IA-86-019",
      title: "Use-of-Force Reporting Review",
      dateLabel: "1986–1987",
      release: "Partially Released",
      status: "CLOSED",
      stamp: "HISTORICAL REVIEW",
      summary: "Department review of inconsistent force-report documentation and supervisor notification.",
      body: [
        "The review found that force incidents were generally documented but not always routed through a consistent supervisory review process.",
        "Several personnel examples were removed from the public copy: {{REDACTED}}. Vance ordered a standardized review form and mandatory supervisor notification for specified incidents.",
      ],
    },
    {
      id: "supervisory-span-audit",
      folder: "Internal Affairs",
      documentCode: "IA-90-027",
      title: "Supervisory Span Audit",
      dateLabel: "1990",
      release: "Public",
      status: "CLOSED",
      stamp: "COMMAND REVIEW",
      summary: "Audit of supervisor-to-deputy ratios as county service demands expanded.",
      body: [
        "The audit found several shifts where one supervisor was responsible for an impractically large geographic area and number of deputies.",
        "Cole recommended additional field-supervisor positions and documented minimum supervisory coverage expectations for each major patrol area.",
      ],
    },
    {
      id: "supervisor-development-program",
      folder: "Achievements",
      documentCode: "ADM-85-014",
      title: "Supervisor Development Program",
      dateLabel: "1985–1988",
      release: "Public",
      stamp: "PERMANENT RETENTION",
      summary: "Formal recurring development program for newly promoted and serving supervisors.",
      body: [
        "The program combined policy instruction with scenario review, report critique, field leadership, and disciplinary fundamentals.",
        "It became the predecessor to later command-development courses and formalized the expectation that promotion carried new training obligations.",
      ],
    },
    {
      id: "county-beat-expansion",
      folder: "Achievements",
      documentCode: "ADM-80-009",
      title: "County Beat Expansion Plan",
      dateLabel: "1980–1983",
      release: "Public",
      stamp: "ARCHIVAL RECORD",
      summary: "Reorganization of patrol beats to keep pace with county growth and service demand.",
      body: [
        "The plan created additional patrol areas, shifted unit start locations, and formalized responsibility for rapidly growing unincorporated communities.",
        "Vance described the expansion as necessary to keep response coverage from being determined solely by where deputies happened to begin a shift.",
      ],
    },
    {
      id: "cole-field-inspection-circular",
      folder: "Correspondence",
      documentCode: "EXEC-CORR-91-033",
      title: "Field Inspection Circular",
      dateLabel: "1991",
      release: "Public",
      stamp: "RECORD COPY",
      summary: "Cole’s command circular setting expectations for field inspections and supervisor presence.",
      body: [
        "Cole instructed supervisors to spend meaningful portions of each shift in the field rather than remaining primarily at offices or stations.",
        "The circular required supervisors to document recurring issues and training needs observed during field contacts, reinforcing the administration’s emphasis on visible supervision.",
      ],
    },
  ],

  "hale-navarro": [
    {
      id: "pacific-transfer-crew",
      folder: "Criminal Organizations",
      documentCode: "ORG-95-018",
      title: "Pacific Transfer Crew",
      dateLabel: "1995–1999",
      release: "Public",
      status: "DISBANDED",
      stamp: "CLOSED INVESTIGATION",
      summary: "Cargo-theft crew targeting transfer yards and short-haul freight routes.",
      body: [
        "The Pacific Transfer Crew used stolen tractors, falsified pickup paperwork, and temporary storage lots to divert legitimate freight.",
        "Investigators later identified several former members as peripheral associates of the Blackwater Group, making the file an important predecessor to Operation Cold Harbor.",
      ],
    },
    {
      id: "copperhead-auto-ring",
      folder: "Criminal Organizations",
      documentCode: "ORG-03-026",
      title: "Copperhead Auto Ring",
      dateLabel: "2003–2007",
      release: "Partially Released",
      status: "DISRUPTED",
      stamp: "PARTIAL RELEASE",
      summary: "Vehicle-cloning and export network operating through repair shops, auctions, and storage yards.",
      body: [
        "The Copperhead Auto Ring specialized in stolen late-model vehicles whose identifiers were altered or paired with salvage paperwork.",
        "A confidential auction-source reference remains {{REDACTED}}. The case resulted in seizures, licensing action, and several prosecutions across multiple jurisdictions.",
      ],
    },
    {
      id: "operation-harbor-line",
      folder: "Operations",
      documentCode: "OP-HL-96",
      title: "Operation Harbor Line",
      dateLabel: "1996–1998",
      release: "Public",
      status: "CLOSED",
      stamp: "AFTER-ACTION FILE",
      summary: "Freight-theft investigation that helped expose links between local cargo crews and the emerging Blackwater Group.",
      body: [
        "Operation Harbor Line tracked diverted loads through storage yards and short-haul trucking companies. Investigators identified recurring names and properties that later appeared in Blackwater intelligence.",
        "The after-action report recommended a shared investigative case index because multiple divisions had independently documented the same subjects.",
      ],
    },
    {
      id: "operation-copper-lane",
      folder: "Operations",
      documentCode: "OP-CL-04",
      title: "Operation Copper Lane",
      dateLabel: "2004–2006",
      release: "Public",
      status: "CLOSED",
      stamp: "CLOSED INVESTIGATION",
      summary: "Vehicle-theft and cloning investigation targeting the Copperhead Auto Ring.",
      body: [
        "Investigators combined DMV records, auction documents, VIN inspection, surveillance, and coordinated warrant service to identify cloned vehicles and storage locations.",
        "The operation became one of the first LSCSO investigations to rely heavily on centralized evidence photographs and shared digital case indexes.",
      ],
    },
    {
      id: "alamo-freight-office-case",
      folder: "Cold Cases",
      documentCode: "CC-02-041",
      title: "Alamo Freight Office Double Homicide",
      dateLabel: "2002",
      release: "Partially Released",
      status: "COLD",
      stamp: "COLD CASE",
      summary: "Unresolved double homicide discovered inside a small freight brokerage office.",
      body: [
        "Two employees were found deceased after failing to answer scheduled dispatch calls. The office showed evidence of a targeted search rather than a broad burglary.",
        "Investigators examined possible ties to freight theft and financial records associated with {{REDACTED}}, but no prosecution followed.",
      ],
    },
    {
      id: "senora-burn-site",
      folder: "Cold Cases",
      documentCode: "CC-06-058",
      title: "Senora Burn Site",
      dateLabel: "2006",
      release: "Public",
      status: "COLD",
      stamp: "COLD CASE",
      summary: "Unidentified burned vehicle and human remains recovered from a remote desert access road.",
      body: [
        "Deputies located a burned vehicle after a utility crew reported smoke damage along an isolated service track. Human remains were recovered but could not be immediately identified.",
        "Vehicle identifiers had been intentionally removed. Later forensic comparison narrowed several possibilities but did not establish a conclusive identity in the historical file.",
      ],
    },
    {
      id: "dispatch-misroute-review",
      folder: "Internal Affairs",
      documentCode: "IA-98-007",
      title: "Dispatch Misroute Review",
      dateLabel: "1998",
      release: "Public",
      status: "CLOSED",
      stamp: "COMMAND REVIEW",
      summary: "Internal review of radio and dispatch failures during a multi-agency pursuit and search.",
      body: [
        "The review found that units from different agencies were using inconsistent channel assignments and location terminology, delaying coordination during a rapidly evolving incident.",
        "No intentional misconduct was identified. Hale used the findings to accelerate interoperability planning and standardize mutual-aid radio procedures.",
      ],
    },
    {
      id: "fleet-procurement-review",
      folder: "Internal Affairs",
      documentCode: "IA-05-024",
      title: "Fleet Procurement Conflict Review",
      dateLabel: "2005",
      release: "Partially Released",
      status: "CLOSED",
      stamp: "PUBLIC RELEASE COPY",
      summary: "Ethics review concerning a procurement employee’s undisclosed relationship with a vehicle vendor.",
      body: [
        "The review determined that a procurement participant failed to disclose a personal relationship relevant to a fleet bid process. The contract itself was re-evaluated and no criminal offense was sustained.",
        "The employee disposition and vendor contact remain {{REDACTED}}. Navarro subsequently required conflict disclosures for specified procurement roles.",
      ],
    },
    {
      id: "regional-radio-plan",
      folder: "Achievements",
      documentCode: "ADM-00-017",
      title: "Regional Radio Interoperability Plan",
      dateLabel: "1999–2002",
      release: "Public",
      stamp: "PERMANENT RETENTION",
      summary: "Joint communications plan improving radio coordination between LSCSO and municipal public-safety agencies.",
      body: [
        "The plan established shared incident channels, common terminology, and procedures for large events requiring multiple agencies.",
        "It was developed alongside equipment modernization and became an important foundation for later joint operations.",
      ],
    },
    {
      id: "evidence-control-manual",
      folder: "Achievements",
      documentCode: "ADM-02-021",
      title: "Evidence Control Manual",
      dateLabel: "2002",
      release: "Public",
      stamp: "PERMANENT RETENTION",
      summary: "Department-wide evidence handling manual created after audits and major multi-agency investigations.",
      body: [
        "The manual standardized packaging, numbering, transfer documentation, temporary storage, supervisory audit requirements, and long-term disposition practices.",
        "Navarro’s implementation memo stated that no division would maintain its own competing evidence numbering system after the transition period.",
      ],
    },
    {
      id: "municipal-chiefs-letter",
      folder: "Correspondence",
      documentCode: "EXEC-CORR-99-040",
      title: "Joint Letter to Municipal Chiefs",
      dateLabel: "1999",
      release: "Public",
      stamp: "RECORD COPY",
      summary: "Hale’s letter proposing regular command coordination and common procedures for major incidents.",
      body: [
        "Hale proposed quarterly command meetings with municipal agencies to discuss communications, pursuits, major investigations, and evidence transfer.",
        "The correspondence marks the beginning of a more formalized interagency relationship that became central during Operation Cold Harbor.",
      ],
    },
  ],

  "mercer-whitaker": [
    {
      id: "south-coast-cargo-exchange",
      folder: "Criminal Organizations",
      documentCode: "ORG-09-012",
      title: "South Coast Cargo Exchange",
      dateLabel: "2009–2013",
      release: "Public",
      status: "DISRUPTED",
      stamp: "CLOSED INVESTIGATION",
      summary: "Freight-theft network using online listings, temporary warehouses, and legitimate trucking accounts.",
      body: [
        "The South Coast Cargo Exchange blended conventional cargo theft with online resale and short-term warehouse leases. Investigators found that stolen goods could be redistributed before paper reports reached every relevant unit.",
        "The case became an early argument for faster shared digital case indexing across LSCSO divisions.",
      ],
    },
    {
      id: "mirrorline-fraud-group",
      folder: "Criminal Organizations",
      documentCode: "ORG-15-024",
      title: "Mirrorline Fraud Group",
      dateLabel: "2015–2019",
      release: "Partially Released",
      status: "DISBANDED",
      stamp: "PARTIAL RELEASE",
      summary: "Fraud organization using stolen identities, falsified business accounts, and staged commercial transactions.",
      body: [
        "Mirrorline used fraudulent business registrations and stolen identity data to obtain goods, credit, and equipment later resold through intermediaries.",
        "Several victim identifiers and one cooperating defendant are {{REDACTED}} in the public archive. The investigation required sustained coordination between investigators, records staff, and outside financial institutions.",
      ],
    },
    {
      id: "operation-copper-clock",
      folder: "Operations",
      documentCode: "OP-CC-10",
      title: "Operation Copper Clock",
      dateLabel: "2010–2011",
      release: "Public",
      status: "CLOSED",
      stamp: "AFTER-ACTION FILE",
      summary: "Regional theft operation targeting organized copper, utility-equipment, and construction-site theft.",
      body: [
        "The operation linked dozens of otherwise minor theft reports through resale locations and common vehicle descriptions. Investigators used shared spreadsheets and centralized briefings to identify patterns that individual districts had missed.",
        "Mercer later cited the case when directing divisions to use common documentation fields for repeat offenders and linked property crimes.",
      ],
    },
    {
      id: "operation-paper-trail",
      folder: "Operations",
      documentCode: "OP-PT-16",
      title: "Operation Paper Trail",
      dateLabel: "2016–2018",
      release: "Partially Released",
      status: "CLOSED",
      stamp: "PUBLIC RELEASE COPY",
      summary: "Financial-fraud investigation targeting the Mirrorline Fraud Group and related shell businesses.",
      body: [
        "Operation Paper Trail combined warrant returns, business filings, financial records, and digital evidence across a two-year investigation.",
        "A cooperating defendant and portions of one financial return remain {{REDACTED}}. The case drove improvements to how digital evidence and financial attachments were indexed inside investigative files.",
      ],
    },
    {
      id: "quarry-twelve-remains",
      folder: "Cold Cases",
      documentCode: "CC-10-016",
      title: "Quarry Twelve Unidentified Remains",
      dateLabel: "2010",
      release: "Public",
      status: "COLD",
      stamp: "UNIDENTIFIED PERSON",
      summary: "Unidentified remains recovered near a disused quarry service road.",
      body: [
        "The remains were discovered during grading work near an old quarry road. Investigators recovered limited personal effects but no identification.",
        "The case was re-entered into newer digital indexes during the Mercer–Whitaker records initiative so future comparisons could be made without relying solely on the original paper file.",
      ],
    },
    {
      id: "vespucci-industrial-fire-case",
      folder: "Cold Cases",
      documentCode: "CC-17-052",
      title: "Vespucci Industrial Fire Death",
      dateLabel: "2017",
      release: "Partially Released",
      status: "COLD",
      stamp: "COLD CASE",
      summary: "Suspicious death discovered after a warehouse fire in an unincorporated industrial area.",
      body: [
        "Fire investigators discovered evidence inconsistent with an accidental ignition after one person was found deceased inside a storage area.",
        "A financial connection to {{REDACTED}} was investigated but never developed into a prosecutable case. The file remains open for periodic review.",
      ],
    },
    {
      id: "training-record-integrity-review",
      folder: "Internal Affairs",
      documentCode: "IA-16-009",
      title: "Training Record Integrity Review",
      dateLabel: "2016",
      release: "Partially Released",
      status: "CLOSED",
      stamp: "REDACTIONS REMAIN",
      summary: "Internal review triggered by inconsistent certification and training-entry records.",
      body: [
        "The inquiry identified duplicated entries, missing source documents, and several training records that could not initially be reconciled with course rosters.",
        "No evidence supported a department-wide falsification scheme. One employee finding remains {{REDACTED}}. Whitaker ordered centralized training records and clearer source-document retention.",
      ],
    },
    {
      id: "complaint-routing-review",
      folder: "Internal Affairs",
      documentCode: "IA-18-021",
      title: "Complaint Routing Review",
      dateLabel: "2018",
      release: "Public",
      status: "CLOSED",
      stamp: "COMMAND REVIEW",
      summary: "Review of how citizen complaints were received, assigned, tracked, and closed across divisions.",
      body: [
        "The review found inconsistent intake practices and uneven documentation of supervisory follow-up. Mercer directed that complaint tracking use a single department-wide workflow regardless of where a complaint originated.",
        "The resulting standards became part of the administration’s broader internal-review reforms.",
      ],
    },
    {
      id: "digital-case-index-rollout",
      folder: "Achievements",
      documentCode: "ADM-15-016",
      title: "Digital Case Index Rollout",
      dateLabel: "2015–2017",
      release: "Public",
      stamp: "PERMANENT RETENTION",
      summary: "Department-wide searchable index connecting major investigative and administrative case references.",
      body: [
        "The rollout allowed investigators and command staff to locate linked case references without relying on separate division spreadsheets and local paper indexes.",
        "The system was intentionally conservative: original documents remained authoritative while the digital index provided searchable references and access controls.",
      ],
    },
    {
      id: "command-leadership-academy",
      folder: "Achievements",
      documentCode: "ADM-17-025",
      title: "Command Leadership Academy",
      dateLabel: "2017",
      release: "Public",
      stamp: "ARCHIVAL RECORD",
      summary: "Formal development program for senior supervisors and future command staff.",
      body: [
        "The academy covered leadership judgment, personnel accountability, administrative law, critical-incident review, ethics, and organizational decision-making.",
        "Mercer described the program as a response to the increasing complexity of command responsibility in a modern Sheriff’s Office.",
      ],
    },
    {
      id: "whitaker-retention-schedule",
      folder: "Correspondence",
      documentCode: "EXEC-CORR-12-014",
      title: "Whitaker Records Retention Schedule Memorandum",
      dateLabel: "2012",
      release: "Public",
      stamp: "RECORD COPY",
      summary: "Executive memorandum establishing common retention schedules for personnel, training, administrative, and investigative records.",
      body: [
        "Whitaker directed divisions to stop treating local convenience copies as permanent record systems and established categories for record retention and archival transfer.",
        "The memorandum is considered a key precursor to LSCSO’s later centralized personnel and command systems.",
      ],
    },
  ],

  "rourke-ellison": [
    {
      id: "high-desert-exchange",
      folder: "Criminal Organizations",
      documentCode: "ORG-21-011",
      title: "High Desert Exchange",
      dateLabel: "2021–2023",
      release: "Partially Released",
      status: "DISRUPTED",
      stamp: "PARTIAL RELEASE",
      summary: "Stolen-property network using rural storage units, private online sales, and temporary resellers.",
      body: [
        "The High Desert Exchange moved stolen tools, electronics, vehicle parts, and commercial equipment through short-lived online accounts and remote storage locations.",
        "Investigators identified overlap with several Canyon Watch associates. One intelligence source remains {{REDACTED}} in the historical release.",
      ],
    },
    {
      id: "redline-vehicle-crew",
      folder: "Criminal Organizations",
      documentCode: "ORG-23-018",
      title: "Redline Vehicle Crew",
      dateLabel: "2023–2025",
      release: "Public",
      status: "DISBANDED",
      stamp: "CLOSED INVESTIGATION",
      summary: "Organized vehicle-theft crew using cloned plates, temporary garages, and rapid parts stripping.",
      body: [
        "The Redline Vehicle Crew targeted higher-value vehicles and moved them through short-term garages before either cloning identifiers or stripping components.",
        "The case was notable because several initial reports had been handled by different divisions under slightly different follow-up practices. The investigation reinforced Rourke’s push for consistent countywide reporting standards.",
      ],
    },
    {
      id: "operation-signal-fire",
      folder: "Operations",
      documentCode: "OP-SF-21",
      title: "Operation Signal Fire",
      dateLabel: "2021–2022",
      release: "Public",
      status: "CLOSED",
      stamp: "AFTER-ACTION FILE",
      summary: "Countywide burglary suppression operation used to test common briefing and supervisor-notification standards.",
      body: [
        "Operation Signal Fire combined patrol saturation, shared intelligence bulletins, and supervisor-led briefings after a series of commercial burglaries affected multiple districts.",
        "The operation’s after-action review found that common briefing formats and required supervisor notifications reduced duplicate investigative work.",
      ],
    },
    {
      id: "operation-switchback",
      folder: "Operations",
      documentCode: "OP-SB-24",
      title: "Operation Switchback",
      dateLabel: "2024–2025",
      release: "Partially Released",
      status: "CLOSED",
      stamp: "PUBLIC RELEASE COPY",
      summary: "Vehicle-trafficking investigation targeting the Redline Vehicle Crew and associated storage locations.",
      body: [
        "Operation Switchback used vehicle records, surveillance, warrant service, and cross-division intelligence to identify staging garages and parts-transfer locations.",
        "One cooperating defendant remains {{REDACTED}} in the public release. The operation produced arrests and recoveries while serving as a test of standardized reporting and command review.",
      ],
    },
    {
      id: "grapeseed-tower-disappearance",
      folder: "Cold Cases",
      documentCode: "CC-23-037",
      title: "Grapeseed Tower Disappearance",
      dateLabel: "2023",
      release: "Partially Released",
      status: "COLD",
      stamp: "COLD CASE",
      summary: "Unresolved disappearance after a late-night cellular-tower maintenance call.",
      body: [
        "A contracted technician failed to return after responding to a reported equipment fault outside Grapeseed. The service vehicle was recovered with tools and personal property still inside.",
        "Digital records established several device connections near the area, but one account holder remains {{REDACTED}} while investigators continue to evaluate the information.",
      ],
    },
    {
      id: "palomino-quarry-homicide",
      folder: "Cold Cases",
      documentCode: "CC-24-046",
      title: "Palomino Quarry Homicide",
      dateLabel: "2024",
      release: "Public",
      status: "COLD",
      stamp: "COLD CASE",
      summary: "Unresolved homicide discovered near a disused quarry access road.",
      body: [
        "The victim was located near a restricted service road after county maintenance personnel found an abandoned personal vehicle nearby.",
        "Investigators developed several leads involving business and personal disputes, but no single theory produced sufficient evidence for arrest. The case remains under periodic review.",
      ],
    },
    {
      id: "report-closure-review",
      folder: "Internal Affairs",
      documentCode: "IA-23-014",
      title: "Report Closure Review",
      dateLabel: "2023",
      release: "Partially Released",
      status: "CLOSED",
      stamp: "REDACTIONS REMAIN",
      summary: "Internal audit of premature or inconsistently documented case closures across several assignments.",
      body: [
        "The audit identified a small number of reports closed without sufficient supervisory documentation and several cases where follow-up responsibility was unclear.",
        "Personnel-specific findings remain {{REDACTED}}. Ellison directed a common closure checklist and supervisor review standard.",
      ],
    },
    {
      id: "supervisor-notification-audit",
      folder: "Internal Affairs",
      documentCode: "IA-24-021",
      title: "Supervisor Notification Audit",
      dateLabel: "2024",
      release: "Public",
      status: "CLOSED",
      stamp: "COMMAND REVIEW",
      summary: "Audit measuring compliance with newly standardized supervisor-notification requirements.",
      body: [
        "The audit reviewed high-liability incidents, pursuits, arrests requiring command notification, and significant personnel events.",
        "Compliance improved throughout the review period, and the final memorandum recommended retaining automated reminders and clearer command escalation paths in future personnel systems.",
      ],
    },
    {
      id: "field-supervisor-standards",
      folder: "Achievements",
      documentCode: "ADM-22-008",
      title: "Field Supervisor Standards",
      dateLabel: "2022",
      release: "Public",
      stamp: "PERMANENT RETENTION",
      summary: "Department-wide expectations for field supervision, incident response, report review, and command notification.",
      body: [
        "The standards clarified when supervisors were expected to respond in person, review reports, document coaching, and elevate significant incidents through command channels.",
        "The document was intentionally written to apply across divisions rather than allowing each assignment to maintain its own informal practices.",
      ],
    },
    {
      id: "training-matrix-rebuild",
      folder: "Achievements",
      documentCode: "ADM-24-019",
      title: "Training Matrix Rebuild",
      dateLabel: "2024–2025",
      release: "Public",
      stamp: "ARCHIVAL RECORD",
      summary: "Reconstruction of department training expectations by rank, assignment, and supervisory responsibility.",
      body: [
        "Ellison directed command staff to identify required, recurring, and assignment-specific training using one common matrix rather than division-maintained lists.",
        "The project improved consistency and provided much of the organizational groundwork later used by the Miller–White administration’s personnel systems.",
      ],
    },
    {
      id: "ellison-modernization-planning-memo",
      folder: "Correspondence",
      documentCode: "EXEC-CORR-25-027",
      title: "Personnel Systems Modernization Planning Memorandum",
      dateLabel: "2025",
      release: "Public",
      stamp: "TRANSFER COPY",
      summary: "Ellison memorandum outlining priorities for the next generation of personnel and command systems.",
      body: [
        "The memorandum identified fragmented personnel records, inconsistent approval routing, and limited command visibility as problems that could no longer be solved by policy alone.",
        "Ellison recommended a unified personnel system with role-based access, audit history, supervisor accountability, and department-wide standards. The document was transferred to the incoming Miller–White administration.",
      ],
    },
  ],
};
