export type ArchiveFolder =
  | "Leadership"
  | "Criminal Organizations"
  | "Operations"
  | "Cold Cases"
  | "Internal Affairs"
  | "Achievements"
  | "Correspondence";

export type ArchiveRelease = "Public" | "Partially Released" | "Sealed";

export type ArchiveRecord = {
  id: string;
  folder: ArchiveFolder;
  documentCode: string;
  title: string;
  dateLabel: string;
  release: ArchiveRelease;
  status?: string;
  stamp?: string;
  summary: string;
  body: string[];
};

export type ArchiveCollection = {
  slug: string;
  sheriff: string;
  undersheriff: string;
  years: string;
  descriptor: string;
  records: ArchiveRecord[];
};

export const archiveCollections: ArchiveCollection[] = [
  {
    slug: "mccall-bell",
    sheriff: "Warren McCall",
    undersheriff: "Arthur Bell",
    years: "1963–1978",
    descriptor: "Founding Administration",
    records: [
      {
        id: "mccall-biography",
        folder: "Leadership",
        documentCode: "EXEC-BIO-001",
        title: "Sheriff Warren McCall",
        dateLabel: "1922–1989",
        release: "Public",
        stamp: "ARCHIVAL RECORD",
        summary: "Founding Sheriff of the Los Santos County Sheriff’s Office.",
        body: [
          "Warren McCall was born in Los Santos County in 1922 and entered county law-enforcement service in 1948. Before the creation of LSCSO, McCall served in a patchwork county constabulary structure where patrol responsibilities, prisoner transport, and rural calls for service were handled with little standardization.",
          "In 1963, McCall was selected to lead the newly established Los Santos County Sheriff’s Office. His administration emphasized a unified patrol model, clear command authority, written reporting standards, and a permanent headquarters. He served until 1978 and remained active in county civic organizations after retirement. McCall died in 1989.",
        ],
      },
      {
        id: "bell-biography",
        folder: "Leadership",
        documentCode: "EXEC-BIO-002",
        title: "Undersheriff Arthur Bell",
        dateLabel: "1927–1991",
        release: "Public",
        stamp: "ARCHIVAL RECORD",
        summary: "The administrator who turned the founding Sheriff’s vision into working procedure.",
        body: [
          "Arthur Bell entered county service in 1952 and spent much of his early career in records, prisoner transport, and field supervision. Bell became known internally for meticulous handwritten logs and an insistence that reports be complete enough for another deputy to understand a case without having been present.",
          "As Undersheriff, Bell built the Office’s first formal duty rosters, report-routing practices, prisoner-handling documentation, and chain-of-command procedures. His administrative work became the backbone of the early Sheriff’s Office. Bell retired alongside McCall in 1978 and died in 1991.",
        ],
      },
      {
        id: "red-mesa-dossier",
        folder: "Criminal Organizations",
        documentCode: "ORG-68-014",
        title: "The Red Mesa Outfit",
        dateLabel: "1968–1974",
        release: "Partially Released",
        status: "DISBANDED",
        stamp: "PARTIAL RELEASE",
        summary: "A rural organized-crime network tied to stolen vehicles, cargo theft, illegal gambling, and public corruption.",
        body: [
          "The Red Mesa Outfit operated across northern Los Santos County through a loose network of repair yards, private clubs, towing companies, and agricultural properties. Investigators linked the group to stolen vehicle re-identification, cargo theft, illegal gambling, and the use of legitimate businesses to conceal proceeds.",
          "A 1970 intelligence memorandum identified {{REDACTED}} as a suspected intermediary between the organization and a county contractor. The individual was never criminally charged. The corresponding witness statement remains restricted to protect surviving family members.",
          "The organization fractured after a series of arrests, licensing actions, and financial seizures between 1971 and 1974. LSCSO later cited the investigation as one of the first cases to demonstrate the need for centralized investigative files and more reliable evidence tracking.",
        ],
      },
      {
        id: "operation-iron-range",
        folder: "Operations",
        documentCode: "OP-IR-69",
        title: "Operation Iron Range",
        dateLabel: "1969–1971",
        release: "Public",
        status: "CLOSED",
        stamp: "CLOSED INVESTIGATION",
        summary: "A long-term operation targeting the Red Mesa Outfit’s vehicle-theft and cargo-fencing network.",
        body: [
          "Operation Iron Range began after patrol deputies identified a recurring pattern of stolen commercial vehicles being recovered stripped on remote county roads. Investigators traced parts and cargo through several repair shops and private storage properties associated with the Red Mesa Outfit.",
          "The operation combined surveillance, controlled property identification, coordinated search warrants, and financial record review. By late 1971, the Sheriff’s Office had recovered stolen vehicles and cargo from multiple properties and referred numerous defendants for prosecution.",
          "An after-action memorandum criticized inconsistent property receipts between patrol and investigators. The McCall–Bell administration responded by ordering a standardized evidence receipt and transfer process department-wide.",
        ],
      },
      {
        id: "dry-creek-file",
        folder: "Cold Cases",
        documentCode: "CC-72-031",
        title: "Dry Creek Disappearance",
        dateLabel: "1972",
        release: "Partially Released",
        status: "COLD",
        stamp: "COLD CASE",
        summary: "The unresolved disappearance of a county survey contractor last seen near Dry Creek Road.",
        body: [
          "On September 18, 1972, a county survey contractor failed to return from a field assignment in the Dry Creek area. The contractor’s vehicle was located the following morning near an abandoned service road with personal property still inside.",
          "Searches continued for several weeks. Investigators documented conflicting witness accounts involving an unidentified pickup truck and a person described only as {{REDACTED}}. No arrest was made and no remains were recovered.",
          "The file was formally moved to inactive status in 1977 and later designated a cold case. Certain witness identifiers remain redacted in the public archive.",
        ],
      },
      {
        id: "property-room-review",
        folder: "Internal Affairs",
        documentCode: "IA-73-006",
        title: "Property Room Ledger Review",
        dateLabel: "1973–1974",
        release: "Partially Released",
        status: "CLOSED",
        stamp: "REDACTIONS REMAIN",
        summary: "An internal inquiry into missing receipt numbers and inconsistent evidence transfers at the original headquarters.",
        body: [
          "A routine administrative inspection in 1973 found gaps in property-room receipt books and several transfers that could not be reconstructed from the paperwork available. No evidence established a broad theft scheme, but the deficiencies were serious enough to trigger an internal review.",
          "Two employees resigned during the review. Findings concerning one former employee remain redacted because the matter did not result in a criminal charge: {{REDACTED}}.",
          "The review produced new requirements for sequential property receipts, supervisor verification of transfers, and periodic ledger reconciliation. Those changes became a direct predecessor to later LSCSO evidence-control policy.",
        ],
      },
      {
        id: "general-order-12-63",
        folder: "Achievements",
        documentCode: "GO-12-63",
        title: "Unified Patrol and Chain of Command",
        dateLabel: "1963",
        release: "Public",
        stamp: "PERMANENT RETENTION",
        summary: "The founding order establishing the first unified LSCSO patrol structure and formal command chain.",
        body: [
          "General Order 12-63 assigned county patrol responsibility through a single Sheriff’s Office structure rather than the fragmented arrangements that preceded LSCSO. The order established duty supervision, report routing, prisoner-transfer responsibility, and a defined command chain.",
          "Later administrations repeatedly cited this order as the beginning of modern department organization. The original signed copy is retained in the executive archive.",
        ],
      },
      {
        id: "headquarters-memo-1963",
        folder: "Correspondence",
        documentCode: "EXEC-CORR-63-004",
        title: "Opening of the Original Headquarters",
        dateLabel: "November 1963",
        release: "Public",
        stamp: "RECORD COPY",
        summary: "Executive correspondence announcing the move into the Office’s first permanent headquarters.",
        body: [
          "McCall’s memorandum instructed all personnel to begin reporting through the new headquarters and directed that arrest records, prisoner logs, and incident reports be centralized there. Bell added a handwritten routing note requiring division supervisors to forward outstanding paper files within thirty days.",
          "The move was modest by later standards, but it marked the first time LSCSO maintained a permanent countywide administrative center.",
        ],
      },
    ],
  },
  {
    slug: "vance-cole",
    sheriff: "Elena Vance",
    undersheriff: "Raymond Cole",
    years: "1978–1994",
    descriptor: "Growth and Professionalization",
    records: [
      {
        id: "vance-biography",
        folder: "Leadership",
        documentCode: "EXEC-BIO-003",
        title: "Sheriff Elena Vance",
        dateLabel: "1938–2010",
        release: "Public",
        stamp: "ARCHIVAL RECORD",
        summary: "Sheriff who led LSCSO through major county growth and expanded field supervision.",
        body: [
          "Elena Vance joined county law enforcement in 1961 and served in patrol, investigations, and administration before succeeding Warren McCall in 1978. Her tenure coincided with significant population growth and a rapidly expanding service area.",
          "Vance expanded patrol coverage, formalized supervisory ranks, and made specialized training a routine expectation rather than an occasional assignment. She retired in 1994 and died in 2010.",
        ],
      },
      {
        id: "cole-biography",
        folder: "Leadership",
        documentCode: "EXEC-BIO-004",
        title: "Undersheriff Raymond Cole",
        dateLabel: "1935–2001",
        release: "Public",
        stamp: "ARCHIVAL RECORD",
        summary: "Field-oriented Undersheriff who standardized supervisor expectations across a growing county.",
        body: [
          "Raymond Cole spent much of his career as a patrol supervisor and was known for conducting unannounced field inspections across remote patrol areas. Vance selected him as Undersheriff in 1978 to give the expanding Office a consistent field-supervision structure.",
          "Cole oversaw the formalization of supervisory ranks, shift briefings, and recurring supervisor development. He retired in 1994 and died in 2001.",
        ],
      },
      {
        id: "marrow-street-dossier",
        folder: "Criminal Organizations",
        documentCode: "ORG-85-022",
        title: "Marrow Street Syndicate",
        dateLabel: "1983–1989",
        release: "Partially Released",
        status: "DISBANDED",
        stamp: "PARTIAL RELEASE",
        summary: "An urban racketeering network connected to theft, extortion, illegal gambling, and commercial intimidation.",
        body: [
          "The Marrow Street Syndicate operated through bars, small freight businesses, private clubs, and several nominally independent crews. Investigators documented a pattern of commercial intimidation, stolen-goods fencing, and gambling activity concentrated in fast-growing urban areas of the county.",
          "A confidential-source appendix identifies several associates who were never charged and remains withheld. The released file substitutes those names with {{REDACTED}}.",
          "The group’s structure largely collapsed by 1989 after convictions, probation violations, and civil licensing actions.",
        ],
      },
      {
        id: "operation-streetlight",
        folder: "Operations",
        documentCode: "OP-ST-86",
        title: "Operation Streetlight",
        dateLabel: "1986–1988",
        release: "Public",
        status: "CLOSED",
        stamp: "CLOSED INVESTIGATION",
        summary: "A multi-year organized-crime investigation targeting the Marrow Street Syndicate.",
        body: [
          "Operation Streetlight combined undercover contacts, surveillance, financial records, and coordinated warrant service. The investigation grew so quickly that case coordination began to exceed the informal supervisory practices then used by several divisions.",
          "The operation resulted in multiple prosecutions and seizures, but its after-action report was equally important internally. It documented duplicated assignments, inconsistent supervisor notification, and conflicting report-routing practices.",
          "Vance used those findings to accelerate formal supervisory ranks and require consistent field supervision across the county.",
        ],
      },
      {
        id: "route-nine-cold-case",
        folder: "Cold Cases",
        documentCode: "CC-87-044",
        title: "Route Nine Courier Case",
        dateLabel: "1987",
        release: "Partially Released",
        status: "COLD",
        stamp: "COLD CASE",
        summary: "An unresolved robbery involving a private commercial courier on County Route Nine.",
        body: [
          "A private courier carrying business receipts disappeared from a scheduled route in October 1987. The vehicle was recovered abandoned several miles from the expected route, but the courier was never located.",
          "Investigators developed two competing suspect theories. One involved members of the Marrow Street Syndicate; the other involved an unrelated acquaintance whose name remains withheld: {{REDACTED}}.",
          "No theory produced sufficient evidence for prosecution. The file remains classified as a cold case.",
        ],
      },
      {
        id: "north-division-review",
        folder: "Internal Affairs",
        documentCode: "IA-84-011",
        title: "North Division Supervision Review",
        dateLabel: "1984",
        release: "Partially Released",
        status: "CLOSED",
        stamp: "PUBLIC RELEASE COPY",
        summary: "A command-directed review of inconsistent field supervision and documentation practices.",
        body: [
          "The review found that several field decisions were being made without consistent supervisor notification and that expectations differed sharply between patrol areas. The report did not identify systemic misconduct, but it concluded that the Office had outgrown informal supervisory practices.",
          "Personnel-specific findings and one disciplinary appendix remain redacted: {{REDACTED}}.",
          "The final recommendations directly supported the expansion of formal supervisory ranks and recurring supervisor training.",
        ],
      },
      {
        id: "field-supervision-directive",
        folder: "Achievements",
        documentCode: "DIR-82-07",
        title: "Field Supervision Directive",
        dateLabel: "1982",
        release: "Public",
        stamp: "PERMANENT RETENTION",
        summary: "Directive establishing consistent shift-level supervisory expectations throughout LSCSO.",
        body: [
          "The directive required clearly designated field supervisors, documented shift briefings, supervisor response to specified high-liability incidents, and formal review of selected deputy reports.",
          "The directive became the framework from which later LSCSO supervision policy developed.",
        ],
      },
      {
        id: "training-expansion-memo",
        folder: "Correspondence",
        documentCode: "EXEC-CORR-87-018",
        title: "Expansion of Specialized Training",
        dateLabel: "1987",
        release: "Public",
        stamp: "RECORD COPY",
        summary: "Executive memorandum making specialized and recurring training a regular part of deputy development.",
        body: [
          "Vance directed command staff to identify recurring training needs rather than relying only on basic academy instruction. Cole’s attached note emphasized supervisor development, report review, and investigative fundamentals.",
          "The memorandum is considered the beginning of LSCSO’s formal continuing-training culture.",
        ],
      },
    ],
  },
  {
    slug: "hale-navarro",
    sheriff: "Robert Hale",
    undersheriff: "Teresa Navarro",
    years: "1994–2009",
    descriptor: "Modern Operational Era",
    records: [
      {
        id: "hale-biography",
        folder: "Leadership",
        documentCode: "EXEC-BIO-005",
        title: "Sheriff Robert Hale",
        dateLabel: "1954–2016",
        release: "Public",
        stamp: "ARCHIVAL RECORD",
        summary: "Modernization-focused Sheriff who reshaped communications, fleet, evidence, and interagency operations.",
        body: [
          "Robert Hale joined LSCSO in 1976 and served in patrol, investigations, and command before becoming Sheriff in 1994. Hale inherited an Office with strong field traditions but increasingly outdated communications and administrative systems.",
          "His administration emphasized radio modernization, evidence procedure, fleet management, investigative coordination, and stronger relationships with municipal public-safety agencies. Hale retired in 2009 and died in 2016.",
        ],
      },
      {
        id: "navarro-biography",
        folder: "Leadership",
        documentCode: "EXEC-BIO-006",
        title: "Undersheriff Teresa Navarro",
        dateLabel: "1957–Present",
        release: "Public",
        stamp: "ARCHIVAL RECORD",
        summary: "Administrative modernizer responsible for consolidating records and tightening evidence accountability.",
        body: [
          "Teresa Navarro entered LSCSO in 1979 and developed a reputation for investigative case management and administrative discipline. Hale selected her as Undersheriff in 1994 with a mandate to modernize the Office’s internal systems.",
          "Navarro oversaw records consolidation, evidence-procedure reform, and several cross-agency planning initiatives. She retired in 2009 and later served in advisory roles connected to county public safety.",
        ],
      },
      {
        id: "blackwater-group-dossier",
        folder: "Criminal Organizations",
        documentCode: "ORG-98-009",
        title: "The Blackwater Group",
        dateLabel: "1997–2004",
        release: "Partially Released",
        status: "DISRUPTED",
        stamp: "PARTIAL RELEASE",
        summary: "A sophisticated theft and racketeering organization operating through freight, storage, and vehicle businesses.",
        body: [
          "The Blackwater Group presented itself as a loose collection of legitimate freight, storage, and automotive businesses. Investigators linked members and associates to organized cargo theft, vehicle cloning, burglary crews, and racketeering activity that crossed municipal boundaries.",
          "Several intelligence-source identities remain sealed. Released copies substitute {{REDACTED}} for those names and remove one financial-account appendix.",
          "The group’s disruption required LSCSO to coordinate evidence, radio traffic, and investigative assignments with multiple municipal agencies, exposing weaknesses that later modernization efforts addressed.",
        ],
      },
      {
        id: "operation-cold-harbor",
        folder: "Operations",
        documentCode: "OP-CH-99",
        title: "Operation Cold Harbor",
        dateLabel: "1999–2003",
        release: "Public",
        status: "CLOSED",
        stamp: "CLOSED INVESTIGATION",
        summary: "Joint investigation that dismantled the core of the Blackwater Group.",
        body: [
          "Operation Cold Harbor became one of the largest multi-agency investigations in LSCSO history to that point. Deputies and partner agencies tracked stolen freight, cloned vehicles, storage locations, and financial connections across several jurisdictions.",
          "The case produced numerous arrests and recoveries, but its administrative legacy was just as significant. Conflicting evidence-label practices and incompatible radio procedures slowed portions of the investigation.",
          "Hale and Navarro used the after-action findings to push standardized evidence procedures, improved radio communications, and formal investigative coordination with municipal agencies.",
        ],
      },
      {
        id: "transfer-yard-seven",
        folder: "Cold Cases",
        documentCode: "CC-97-062",
        title: "Transfer Yard Seven",
        dateLabel: "1997",
        release: "Partially Released",
        status: "COLD",
        stamp: "COLD CASE",
        summary: "An unresolved armed robbery at an industrial transfer yard with suspected organized-crime links.",
        body: [
          "An overnight armed robbery at Transfer Yard Seven resulted in a large commercial cargo loss and the disappearance of a contracted night supervisor. Evidence suggested inside knowledge of shipping schedules, but no employee was charged.",
          "Later Blackwater Group intelligence contained references to a participant known only as {{REDACTED}}. Investigators could not establish the person’s identity or connect the reference conclusively to the robbery.",
          "The case remains open as a cold case and is periodically reviewed when new organized-crime intelligence is archived.",
        ],
      },
      {
        id: "evidence-room-three-audit",
        folder: "Internal Affairs",
        documentCode: "IA-01-019",
        title: "Evidence Room Three Audit",
        dateLabel: "2001",
        release: "Partially Released",
        status: "CLOSED",
        stamp: "REDACTIONS REMAIN",
        summary: "A department-wide evidence audit triggered by discrepancies identified during Operation Cold Harbor.",
        body: [
          "The audit identified inconsistent packaging, duplicate local numbering systems, and several items whose chain-of-custody documentation required reconstruction. The review did not find widespread intentional misconduct, but it concluded that decentralized evidence practices created unacceptable risk.",
          "One personnel finding and a related disciplinary disposition remain redacted: {{REDACTED}}.",
          "Navarro ordered a single evidence-control standard and recurring supervisory audits. Those reforms remained in place long after the individual discrepancies were resolved.",
        ],
      },
      {
        id: "records-consolidation-initiative",
        folder: "Achievements",
        documentCode: "ADM-04-003",
        title: "Records Consolidation Initiative",
        dateLabel: "2004–2007",
        release: "Public",
        stamp: "PERMANENT RETENTION",
        summary: "Project that consolidated administrative and investigative records previously maintained independently by divisions.",
        body: [
          "The initiative created standardized record categories, retention practices, and centralized indexing for material that had previously been stored independently by divisions. The project reduced duplicate files and made cross-division investigative review substantially easier.",
          "This work became the organizational predecessor to the digital centralization undertaken by the Mercer–Whitaker administration.",
        ],
      },
      {
        id: "radio-modernization-memo",
        folder: "Correspondence",
        documentCode: "EXEC-CORR-98-026",
        title: "Countywide Radio Modernization",
        dateLabel: "1998",
        release: "Public",
        stamp: "RECORD COPY",
        summary: "Executive correspondence directing communications upgrades and improved interoperability with municipal agencies.",
        body: [
          "Hale directed command staff to replace aging radio equipment and develop procedures for coordinated incidents involving municipal agencies. Navarro’s implementation note required that the project include written communications protocols, not merely new hardware.",
          "The modernization program was phased in over several years and became essential during later multi-agency investigations.",
        ],
      },
    ],
  },
  {
    slug: "mercer-whitaker",
    sheriff: "Daniel Mercer",
    undersheriff: "James Whitaker",
    years: "2009–2021",
    descriptor: "Accountability and Digital Transition",
    records: [
      {
        id: "mercer-biography",
        folder: "Leadership",
        documentCode: "EXEC-BIO-007",
        title: "Sheriff Daniel Mercer",
        dateLabel: "1968–Present",
        release: "Public",
        stamp: "ARCHIVAL RECORD",
        summary: "Accountability-focused Sheriff who standardized documentation and pushed leadership development.",
        body: [
          "Daniel Mercer joined LSCSO in 1989 and rose through patrol supervision and command assignments. By the time he became Sheriff in 2009, the Office had modernized many operational systems but still relied on inconsistent documentation and locally maintained administrative records.",
          "Mercer emphasized leadership development, internal review, standardized documentation, and greater organizational accountability. He retired in 2021.",
        ],
      },
      {
        id: "whitaker-biography",
        folder: "Leadership",
        documentCode: "EXEC-BIO-008",
        title: "Undersheriff James Whitaker",
        dateLabel: "1966–Present",
        release: "Public",
        stamp: "ARCHIVAL RECORD",
        summary: "Systems-minded Undersheriff who led the transition toward centralized digital records.",
        body: [
          "James Whitaker entered county service in 1987 and served in records, investigations, and command. Mercer appointed him Undersheriff in 2009 with responsibility for internal systems and administrative modernization.",
          "Whitaker oversaw the gradual movement of personnel, training, and administrative records into centralized digital systems while retaining historical paper records under formal retention schedules. He retired in 2021.",
        ],
      },
      {
        id: "glass-ledger-network",
        folder: "Criminal Organizations",
        documentCode: "ORG-11-017",
        title: "Glass Ledger Network",
        dateLabel: "2010–2015",
        release: "Partially Released",
        status: "DISRUPTED",
        stamp: "PARTIAL RELEASE",
        summary: "A financial and racketeering network that used small businesses and freight companies to conceal criminal proceeds.",
        body: [
          "The Glass Ledger Network relied less on visible street activity than prior organized-crime groups. Investigators documented layered business ownership, fraudulent invoices, stolen cargo, and coordinated financial transfers between otherwise unrelated companies.",
          "Several cooperating-witness identities remain restricted. Public copies replace those names and one financial institution reference with {{REDACTED}}.",
          "The investigation pushed LSCSO toward better digital case indexing because analysts were routinely comparing records produced by different divisions over several years.",
        ],
      },
      {
        id: "operation-glass-ledger",
        folder: "Operations",
        documentCode: "OP-GL-12",
        title: "Operation Glass Ledger",
        dateLabel: "2012–2014",
        release: "Public",
        status: "CLOSED",
        stamp: "CLOSED INVESTIGATION",
        summary: "Long-form financial and organized-crime investigation targeting the Glass Ledger Network.",
        body: [
          "Operation Glass Ledger combined conventional surveillance with financial analysis, digital document review, and cross-division case indexing. The investigation produced multiple prosecutions and the seizure of assets associated with fraudulent business activity and organized theft.",
          "The operation revealed how difficult it had become to compare personnel, training, intelligence, and investigative records stored in different systems. Mercer authorized a department-wide documentation standard and Whitaker accelerated central digital indexing.",
        ],
      },
      {
        id: "warehouse-41",
        folder: "Cold Cases",
        documentCode: "CC-11-028",
        title: "Warehouse 41 Disappearance",
        dateLabel: "2011",
        release: "Partially Released",
        status: "COLD",
        stamp: "COLD CASE",
        summary: "Unresolved disappearance connected to an abandoned warehouse and a series of fraudulent freight records.",
        body: [
          "A freight broker disappeared after arranging a late-night meeting at Warehouse 41. The warehouse was found vacant except for discarded shipping paperwork and a recently removed surveillance recorder.",
          "Investigators later discovered that several invoices matched entities connected to the Glass Ledger Network, but no physical evidence established who attended the meeting. One witness account remains restricted: {{REDACTED}}.",
          "The case remains open as a cold case and is retained with related organized-crime intelligence.",
        ],
      },
      {
        id: "administrative-access-review",
        folder: "Internal Affairs",
        documentCode: "IA-14-014",
        title: "Administrative Access Review",
        dateLabel: "2014",
        release: "Partially Released",
        status: "CLOSED",
        stamp: "PUBLIC RELEASE COPY",
        summary: "Internal review of unauthorized access to administrative records during the Office’s digital transition.",
        body: [
          "The review began after an employee accessed administrative records unrelated to assigned duties. Investigators determined that the legacy digital system provided broader access than operationally necessary and lacked useful audit detail.",
          "The employee disposition is redacted in the public copy: {{REDACTED}}.",
          "Mercer ordered tighter role-based access, routine audit review, and clearer accountability for administrative systems. The case strongly influenced later portal-security expectations.",
        ],
      },
      {
        id: "central-records-initiative",
        folder: "Achievements",
        documentCode: "ADM-13-008",
        title: "Central Records Initiative",
        dateLabel: "2013–2018",
        release: "Public",
        stamp: "PERMANENT RETENTION",
        summary: "Multi-year effort to centralize personnel, training, and administrative records into digital systems.",
        body: [
          "The Central Records Initiative replaced numerous division-maintained spreadsheets, local folders, and paper indexes with shared department systems. Records were migrated in phases to avoid losing historical context and to preserve older source documents.",
          "The initiative did not eliminate paper records, but it established the expectation that authoritative personnel and administrative records should be centrally maintained and auditable.",
        ],
      },
      {
        id: "leadership-development-letter",
        folder: "Correspondence",
        documentCode: "EXEC-CORR-16-021",
        title: "Leadership Development Program",
        dateLabel: "2016",
        release: "Public",
        stamp: "RECORD COPY",
        summary: "Command letter establishing expanded leadership development for supervisors and command staff.",
        body: [
          "Mercer wrote that technical competence alone was insufficient for supervisory service and directed the development of recurring leadership instruction. Whitaker’s implementation memorandum added documentation, internal review, and decision accountability to the curriculum.",
          "The program became a routine component of supervisor development during the remainder of the administration.",
        ],
      },
    ],
  },
  {
    slug: "rourke-ellison",
    sheriff: "Thomas Rourke",
    undersheriff: "Marcus Ellison",
    years: "2021–2026",
    descriptor: "Standardization and Transition",
    records: [
      {
        id: "rourke-biography",
        folder: "Leadership",
        documentCode: "EXEC-BIO-009",
        title: "Sheriff Thomas Rourke",
        dateLabel: "1973–Present",
        release: "Public",
        stamp: "ARCHIVAL RECORD",
        summary: "Field-focused Sheriff who rebuilt consistency across divisions and prepared LSCSO for broader modernization.",
        body: [
          "Thomas Rourke joined LSCSO in the mid-1990s and spent much of his career in patrol and field command. He became Sheriff in 2021 at a time when the Office’s divisions had developed uneven practices despite strong underlying policy and technology.",
          "Rourke emphasized field supervision, clearer expectations, updated training, and rebuilding department-wide standards. He left office in 2026 after overseeing the transition toward a more unified personnel and command structure.",
        ],
      },
      {
        id: "ellison-biography",
        folder: "Leadership",
        documentCode: "EXEC-BIO-010",
        title: "Undersheriff Marcus Ellison",
        dateLabel: "1975–Present",
        release: "Public",
        stamp: "ARCHIVAL RECORD",
        summary: "Administrative and training leader who helped convert reform goals into standardized practice.",
        body: [
          "Marcus Ellison entered LSCSO in 1998 and served in training, patrol supervision, and command assignments. Rourke selected him as Undersheriff in 2021 to coordinate department-wide standardization.",
          "Ellison oversaw revised training practices, clearer operational expectations, and early planning for modern personnel-management systems. He left executive office with Rourke in 2026.",
        ],
      },
      {
        id: "canyon-watch-crew",
        folder: "Criminal Organizations",
        documentCode: "ORG-22-005",
        title: "Canyon Watch Crew",
        dateLabel: "2021–2024",
        release: "Partially Released",
        status: "DISRUPTED",
        stamp: "PARTIAL RELEASE",
        summary: "Organized burglary and vehicle-trafficking crew operating from remote county properties.",
        body: [
          "The Canyon Watch Crew used temporary storage sites, stolen vehicles, and rapidly changing associates to support commercial burglaries and vehicle trafficking. Investigators believed the group deliberately exploited differences in reporting and follow-up practices between divisions.",
          "One cooperating source and several intelligence-only associates remain withheld from the public release: {{REDACTED}}.",
          "The investigation became an internal case study for why department-wide standards had to be applied consistently regardless of assignment or geography.",
        ],
      },
      {
        id: "operation-canyon-watch",
        folder: "Operations",
        documentCode: "OP-CW-22",
        title: "Operation Canyon Watch",
        dateLabel: "2022–2023",
        release: "Public",
        status: "CLOSED",
        stamp: "CLOSED INVESTIGATION",
        summary: "Coordinated burglary and vehicle-trafficking investigation that tested newly standardized field procedures.",
        body: [
          "Operation Canyon Watch paired patrol intelligence, investigators, vehicle records, and coordinated warrant service. Rourke required the operation to use a single reporting and supervisory structure rather than division-specific practices.",
          "The operation resulted in arrests, property recovery, and the closure of several remote storage locations. Its after-action review found that standardized supervisor notifications and common documentation significantly reduced duplicated work.",
        ],
      },
      {
        id: "route-68-night-run",
        folder: "Cold Cases",
        documentCode: "CC-22-019",
        title: "Route 68 Night Run",
        dateLabel: "2022",
        release: "Partially Released",
        status: "COLD",
        stamp: "COLD CASE",
        summary: "Unresolved disappearance involving an abandoned vehicle recovered along Route 68.",
        body: [
          "A vehicle was found abandoned overnight along Route 68 after its registered driver failed to arrive at a scheduled destination. Digital and witness evidence established the vehicle’s approximate route but not the circumstances of the disappearance.",
          "A later tip referenced a property associated with {{REDACTED}}, but searches did not locate evidence sufficient to establish involvement.",
          "The case remains under periodic review and is retained as an active cold-case file.",
        ],
      },
      {
        id: "division-consistency-review",
        folder: "Internal Affairs",
        documentCode: "IA-21-003",
        title: "Division Consistency Review",
        dateLabel: "2021–2022",
        release: "Partially Released",
        status: "CLOSED",
        stamp: "REDACTIONS REMAIN",
        summary: "Executive review of inconsistent field, training, and supervisory practices inherited across divisions.",
        body: [
          "The review compared field supervision, training documentation, report expectations, and personnel practices across divisions. It found that many differences were historical rather than intentional, but that inconsistent expectations were undermining command accountability.",
          "A sealed executive appendix addressed personnel-specific conduct and remains unavailable for public review. The released copy marks that appendix as {{REDACTED}}.",
          "The findings became the blueprint for Rourke–Ellison standardization efforts and later modernization of personnel-management systems.",
        ],
      },
      {
        id: "department-standards-rebuild",
        folder: "Achievements",
        documentCode: "ADM-23-012",
        title: "Department Standards Rebuild",
        dateLabel: "2022–2025",
        release: "Public",
        stamp: "PERMANENT RETENTION",
        summary: "Multi-year effort to align supervision, training, documentation, and operational expectations across LSCSO.",
        body: [
          "The rebuild standardized recurring training expectations, clarified supervisor responsibilities, and aligned core documentation practices across divisions. Command staff were directed to identify legacy practices that conflicted with current department standards.",
          "The project laid much of the organizational groundwork later used by the Miller–White administration for personnel and command modernization.",
        ],
      },
      {
        id: "transition-memorandum-2026",
        folder: "Correspondence",
        documentCode: "EXEC-CORR-26-002",
        title: "Executive Transition Memorandum",
        dateLabel: "2026",
        release: "Partially Released",
        stamp: "TRANSFER COPY",
        summary: "Outgoing executive memorandum transferring modernization priorities and unresolved administrative work to the incoming administration.",
        body: [
          "Rourke and Ellison’s transition memorandum identified personnel development, command accessibility, documentation consistency, and modernization of personnel-management systems as unfinished priorities requiring continued executive attention.",
          "One attachment concerning an active personnel matter remains sealed and is represented in the public copy as {{REDACTED}}.",
          "The memorandum was transferred to the Miller–White administration as part of the 2026 executive transition file.",
        ],
      },
    ],
  },
];

export const archiveFolders: ArchiveFolder[] = [
  "Leadership",
  "Criminal Organizations",
  "Operations",
  "Cold Cases",
  "Internal Affairs",
  "Achievements",
  "Correspondence",
];

export const getArchiveCollection = (slug: string | null) =>
  archiveCollections.find((collection) => collection.slug === slug) ?? null;
