import type { ArchiveFolder, ArchiveRecord } from "./archive-canon";

const artifactFolder = "Photos & Artifacts" as ArchiveFolder;

export const archiveArtifactRecords: Record<string, ArchiveRecord[]> = {
  "mccall-bell": [
    {
      id: "founding-command-portrait-1963",
      folder: artifactFolder,
      documentCode: "ART-63-001",
      title: "Founding Command Portrait",
      dateLabel: "1963",
      release: "Public",
      status: "ACCESSIONED",
      stamp: "PHOTOGRAPHIC HOLDING",
      summary: "Formal black-and-white command portrait of Sheriff Warren McCall and Undersheriff Arthur Bell during LSCSO’s founding year.",
      body: [
        "The photograph was taken shortly after the Los Santos County Sheriff’s Office became a permanent county law-enforcement organization. McCall and Bell are pictured inside the original headquarters with the first Office seal displayed between them.",
        "The print remained in the executive hallway for decades before being transferred to archival storage. A preservation scan is maintained with the original fiber-based photographic print.",
      ],
    },
    {
      id: "first-duty-roster-ledger",
      folder: artifactFolder,
      documentCode: "ART-63-004",
      title: "First Countywide Duty Roster Ledger",
      dateLabel: "1963–1964",
      release: "Public",
      status: "PERMANENT HOLDING",
      stamp: "ARCHIVAL OBJECT",
      summary: "Bound duty-roster ledger used by Arthur Bell to organize the earliest unified patrol assignments.",
      body: [
        "The ledger contains handwritten shift assignments, supervisor notations, prisoner-transport responsibilities, and mileage entries from LSCSO’s first year. Several pages include Bell’s routing marks showing where deputies were reassigned as county calls increased.",
        "The original volume is retained in a protective enclosure because repeated handling caused wear along the spine and page edges.",
      ],
    },
    {
      id: "patrol-radio-unit-14",
      folder: artifactFolder,
      documentCode: "ART-66-009",
      title: "Patrol Radio Unit No. 14",
      dateLabel: "1966",
      release: "Public",
      status: "DECOMMISSIONED",
      stamp: "EQUIPMENT HOLDING",
      summary: "Early mobile radio assembly preserved from one of LSCSO’s first standardized patrol vehicles.",
      body: [
        "The unit was removed from service after later communications upgrades but retained because it represents the Office’s earliest effort to maintain reliable countywide patrol contact.",
        "An inventory tag attached during a 1989 historical-property review identifies the radio as equipment formerly assigned to northern county patrol operations.",
      ],
    },
  ],
  "vance-cole": [
    {
      id: "north-division-patrol-map",
      folder: artifactFolder,
      documentCode: "ART-82-013",
      title: "North Division Patrol Map",
      dateLabel: "1982",
      release: "Public",
      status: "ACCESSIONED",
      stamp: "MAP HOLDING",
      summary: "Large wall map marked by hand to document expanded patrol sectors during rapid county growth.",
      body: [
        "Colored grease-pencil marks identify revised patrol sectors, supervisor response areas, and recurring call locations. The map was used during the Vance–Cole expansion of countywide field supervision.",
        "Later annotations show how temporary sectors became formalized as service demand increased through the 1980s.",
      ],
    },
    {
      id: "supervisor-training-contact-sheet",
      folder: artifactFolder,
      documentCode: "ART-88-021",
      title: "Supervisor Training Contact Sheet",
      dateLabel: "1988",
      release: "Public",
      status: "PRESERVATION COPY",
      stamp: "PHOTOGRAPHIC HOLDING",
      summary: "Contact sheet from an early recurring supervisor-development course established during the Vance administration.",
      body: [
        "The photographs show classroom instruction, report-review exercises, and field briefing scenarios used to standardize supervisory expectations across patrol areas.",
        "The original negatives are retained separately; the archive displays a preservation contact sheet created during later photographic rehousing.",
      ],
    },
    {
      id: "field-supervisor-insignia-set",
      folder: artifactFolder,
      documentCode: "ART-79-006",
      title: "Early Field Supervisor Insignia Set",
      dateLabel: "1979",
      release: "Public",
      status: "ACCESSIONED",
      stamp: "UNIFORM HOLDING",
      summary: "Retired rank and collar insignia associated with the formalization of supervisory ranks under Vance and Cole.",
      body: [
        "The insignia set was retained by Training after uniform specifications changed. Its archival card notes that the pieces were used during the first period in which LSCSO consistently distinguished formal field-supervisory assignments across divisions.",
      ],
    },
  ],
  "hale-navarro": [
    {
      id: "cold-harbor-contact-sheet",
      folder: artifactFolder,
      documentCode: "ART-CH-01",
      title: "Operation Cold Harbor Evidence Contact Sheet",
      dateLabel: "2001",
      release: "Partially Released",
      status: "RELEASE COPY",
      stamp: "REDACTIONS REMAIN",
      summary: "Released photographic contact sheet documenting warrant locations, recovered freight, and vehicle evidence from Operation Cold Harbor.",
      body: [
        "The original investigative set contains photographs from multiple agencies. The public archive copy removes images that reveal confidential-source locations and identifying information associated with uninvolved persons.",
        "Frames corresponding to restricted locations are marked {{REDACTED}} in the released index.",
      ],
    },
    {
      id: "interoperability-radio-console",
      folder: artifactFolder,
      documentCode: "ART-00-017",
      title: "Interagency Radio Interoperability Console",
      dateLabel: "2000–2004",
      release: "Public",
      status: "DECOMMISSIONED",
      stamp: "EQUIPMENT HOLDING",
      summary: "Decommissioned communications console component preserved from the Hale–Navarro radio-modernization program.",
      body: [
        "The equipment supported improved coordination between LSCSO and municipal public-safety agencies during large incidents and joint investigations.",
        "A maintenance card attached to the unit records several upgrades made after communication problems documented during early Cold Harbor operations.",
      ],
    },
    {
      id: "fleet-modernization-photo-set",
      folder: artifactFolder,
      documentCode: "ART-96-011",
      title: "Fleet Modernization Evaluation Photographs",
      dateLabel: "1996",
      release: "Public",
      status: "ARCHIVED",
      stamp: "PHOTOGRAPHIC HOLDING",
      summary: "Photograph set documenting patrol-vehicle and equipment evaluations conducted during early fleet modernization.",
      body: [
        "The set includes comparison photographs of equipment placement, emergency-light configurations, prisoner partitions, and early mobile-computing mounts.",
        "Navarro’s handwritten notes on the accompanying index emphasize maintainability and consistent equipment placement across the fleet.",
      ],
    },
  ],
  "mercer-whitaker": [
    {
      id: "central-records-backup-disc",
      folder: artifactFolder,
      documentCode: "ART-13-024",
      title: "Central Records Migration Backup Set",
      dateLabel: "2013",
      release: "Public",
      status: "PRESERVATION OBJECT",
      stamp: "DIGITAL MEDIA HOLDING",
      summary: "Optical-media backup set retained from an early phase of LSCSO’s centralized digital-records migration.",
      body: [
        "The discs no longer function as an authoritative department system and are not used for operational recovery. They are retained as artifacts documenting the Office’s transition away from locally maintained administrative files.",
        "The archival set contains no publicly readable personnel data; preservation documentation records the migration process and media identifiers only.",
      ],
    },
    {
      id: "leadership-program-binder",
      folder: artifactFolder,
      documentCode: "ART-16-031",
      title: "Leadership Development Instructor Binder",
      dateLabel: "2016",
      release: "Public",
      status: "ACCESSIONED",
      stamp: "TRAINING HOLDING",
      summary: "Instructor binder from the expanded supervisor and command leadership-development program.",
      body: [
        "The binder contains lesson outlines on decision accountability, documentation, internal review, and supervisory judgment. Margin notes show revisions made after the program’s first command-staff sessions.",
      ],
    },
    {
      id: "glass-ledger-digital-evidence-envelope",
      folder: artifactFolder,
      documentCode: "ART-GL-14",
      title: "Glass Ledger Digital Evidence Envelope",
      dateLabel: "2014",
      release: "Partially Released",
      status: "CLOSED CASE HOLDING",
      stamp: "PUBLIC DISPLAY COPY",
      summary: "Preservation display copy of a digital-evidence envelope used during Operation Glass Ledger.",
      body: [
        "The original media remains governed by evidence-retention rules. The archival display copy preserves the labeling format and chain-of-custody design used during the investigation without exposing stored case data.",
        "One original evidence identifier is withheld from the public copy as {{REDACTED}}.",
      ],
    },
  ],
  "rourke-ellison": [
    {
      id: "standards-rebuild-command-binder",
      folder: artifactFolder,
      documentCode: "ART-22-018",
      title: "Department Standards Rebuild Command Binder",
      dateLabel: "2022–2025",
      release: "Public",
      status: "ACCESSIONED",
      stamp: "EXECUTIVE HOLDING",
      summary: "Working command binder used to track department-wide standardization projects during the Rourke–Ellison administration.",
      body: [
        "Tabs divide the binder into supervision, training, documentation, division practices, and implementation follow-up. Many pages carry dated routing notes showing when legacy practices were reviewed or replaced.",
        "The binder is retained because it documents the practical work behind the administration’s standards rebuild rather than only the final published directives.",
      ],
    },
    {
      id: "canyon-watch-warrant-board-photo",
      folder: artifactFolder,
      documentCode: "ART-CW-23",
      title: "Operation Canyon Watch Coordination Board Photograph",
      dateLabel: "2023",
      release: "Partially Released",
      status: "RELEASE COPY",
      stamp: "REDACTIONS REMAIN",
      summary: "Command-post photograph showing the coordination board used during warrant-service planning for Operation Canyon Watch.",
      body: [
        "The released image preserves the layout of assignments, timelines, and supervisory checkpoints while masking addresses and identifiers tied to private persons.",
        "Several sections of the board remain {{REDACTED}} in the public preservation copy.",
      ],
    },
    {
      id: "executive-transition-box-seal",
      folder: artifactFolder,
      documentCode: "ART-26-002",
      title: "2026 Executive Transition Archive Seal",
      dateLabel: "2026",
      release: "Public",
      status: "TRANSFERRED",
      stamp: "ACCESSION RECORD",
      summary: "Tamper-evident archive seal and accession card from the executive records transferred at the end of the Rourke–Ellison administration.",
      body: [
        "The seal was removed when the historical portion of the outgoing executive collection was accessioned. The accompanying card records the transfer date, box sequence, and the existence of a separately controlled personnel appendix.",
        "The item marks the physical transition between the Rourke–Ellison collection and the still-active Miller–White administration records.",
      ],
    },
  ],
};
