export const APPLICATION_STATUSES = ["Submitted", "Under Review", "Interview", "Accepted", "Denied", "Withdrawn"] as const;
export const INTERVIEW_STATUSES = ["Not Scheduled", "Scheduled", "Completed", "No Show", "Passed", "Failed"] as const;

export const applicationQuestions: Array<[string, string, string]> = [
  ["Applicant Information", "full_name", "What is your full name?"], ["Applicant Information", "discord_username", "What is your Discord username?"], ["Applicant Information", "age", "What is your age?"], ["Applicant Information", "timezone", "What is your timezone?"], ["Applicant Information", "fivem_experience", "How long have you been playing FiveM?"], ["Applicant Information", "serious_rp_experience", "How long have you been participating in serious roleplay?"],
  ["Availability", "weekly_hours", "How many hours per week can you dedicate to LSCSO?"], ["Availability", "upcoming_commitments", "Do you have any upcoming commitments that may affect your activity?"], ["Availability", "mandatory_training", "Are you willing to attend mandatory department meetings or training when required?"],
  ["Roleplay Experience", "previous_departments", "What departments or factions have you previously been a member of?"], ["Roleplay Experience", "previous_ranks", "What ranks have you held in previous communities?"], ["Roleplay Experience", "supervisory_experience", "Have you previously held a supervisory or command position? If so, explain."], ["Roleplay Experience", "serious_roleplay_definition", "What does serious roleplay mean to you?"], ["Roleplay Experience", "good_le_roleplayer", "What makes a good law enforcement roleplayer?"],
  ["LSCSO Interest", "why_lscso", "Why do you want to join the Los Santos County Sheriff's Office?"], ["LSCSO Interest", "lscso_goals", "What do you hope to accomplish during your time with LSCSO?"], ["LSCSO Interest", "career_path", "What position or career path within LSCSO interests you most?"], ["LSCSO Interest", "department_expectations", "What do you expect from LSCSO as a department?"], ["LSCSO Interest", "contribution", "What do you believe you can contribute to LSCSO?"],
  ["Law Enforcement Knowledge", "reasonable_suspicion_probable_cause", "Explain the difference between reasonable suspicion and probable cause."], ["Law Enforcement Knowledge", "officer_discretion", "When should an officer use discretion?"], ["Law Enforcement Knowledge", "use_of_force_factors", "What factors should an officer consider before using force?"], ["Law Enforcement Knowledge", "radio_communication", "Why is proper radio communication important?"],
  ["Scenario Questions", "scenario_speeding_nervous", "You stop a vehicle for speeding. The driver is cooperative but becomes increasingly nervous during the stop. What do you do?"], ["Scenario Questions", "scenario_fleeing_vehicle", "You are conducting a traffic stop when the driver suddenly takes off. What are your priorities?"], ["Scenario Questions", "scenario_warrant", "You pull over a vehicle and discover the driver has an outstanding warrant. Explain how you would proceed."], ["Scenario Questions", "scenario_deputy_policy_violation", "You witness another deputy violating department policy. What do you do?"], ["Scenario Questions", "scenario_supervisor_order", "A supervisor orders you to do something that you believe violates department policy. How do you handle it?"],
  ["Integrity & Professionalism", "prior_discipline", "Have you ever been removed, suspended, banned, or terminated from a FiveM community?"], ["Integrity & Professionalism", "prior_discipline_explanation", "If yes, explain."], ["Integrity & Professionalism", "breaking_character", "Have you ever intentionally broken character to gain an advantage in a roleplay situation? Explain."], ["Integrity & Professionalism", "friend_policy_violation", "What would you do if your friend was caught violating department policy?"], ["Integrity & Professionalism", "protect_fellow_officer", "Is there ever a situation where protecting a fellow officer is more important than following department policy? Explain."], ["Integrity & Professionalism", "honesty_importance", "Why is honesty important when applying to a law enforcement department? Explain."],
  ["Final Questions", "anything_else", "Is there anything else you would like the LSCSO command staff to know about you?"], ["Final Questions", "self_improvement", "What is one thing you believe you could improve about yourself?"], ["Final Questions", "policy_agreement", "Do you agree to follow all LSCSO policies, procedures, orders, and training requirements?"],
];

export function applicationLabel(applicationNumber: number | string) { return `APP-${String(applicationNumber).padStart(4, "0")}`; }
