-- Incremental command-review workflow for public recruitment applications.
alter table public.recruitment_applications
  add column if not exists applicant_auth_user_id uuid references auth.users(id) on delete set null,
  add column if not exists submitted_at timestamptz,
  add column if not exists decided_by_profile_id uuid references public.personnel_profiles(id),
  add column if not exists interview_scheduled_at timestamptz,
  add column if not exists interviewer_profile_id uuid references public.personnel_profiles(id),
  add column if not exists interview_status text not null default 'Not Scheduled'
    check (interview_status in ('Not Scheduled','Scheduled','Completed','No Show','Passed','Failed')),
  add column if not exists interview_notes text,
  add column if not exists interview_result text;

-- "Submitted" is the public-facing replacement for the original Pending status.
alter table public.recruitment_applications
  drop constraint if exists recruitment_applications_status_check;
alter table public.recruitment_applications
  add constraint recruitment_applications_status_check
  check (status in ('Submitted','Under Review','Interview','Accepted','Denied','Withdrawn','Archived'));
update public.recruitment_applications set status = 'Submitted' where status = 'Pending';
update public.recruitment_applications set submitted_at = created_at where submitted_at is null;
alter table public.recruitment_applications alter column submitted_at set default now();
alter table public.recruitment_applications alter column submitted_at set not null;

-- Public submission is deliberately mediated by the server route, which validates
-- content, duplicate attempts, and notification delivery without exposing the table.
drop policy if exists recruitment_applications_public_insert on public.recruitment_applications;

create table if not exists public.recruitment_application_notes (
  id uuid primary key default gen_random_uuid(),
  application_id uuid not null references public.recruitment_applications(id) on delete cascade,
  author_profile_id uuid not null references public.personnel_profiles(id) on delete restrict,
  content text not null check (char_length(trim(content)) between 1 and 8000),
  created_at timestamptz not null default now()
);

create table if not exists public.recruitment_application_history (
  id bigint generated by default as identity primary key,
  application_id uuid not null references public.recruitment_applications(id) on delete cascade,
  actor_profile_id uuid references public.personnel_profiles(id) on delete set null,
  event_type text not null check (event_type in (
    'Submitted','Reviewer Assigned','Status Changed','Interview Updated','Note Added','Accepted','Denied'
  )),
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists recruitment_applications_reviewer_idx on public.recruitment_applications (reviewer_profile_id, updated_at desc);
create index if not exists recruitment_applications_applicant_auth_idx on public.recruitment_applications (applicant_auth_user_id, submitted_at desc) where applicant_auth_user_id is not null;
create index if not exists recruitment_application_notes_application_idx on public.recruitment_application_notes (application_id, created_at desc);
create index if not exists recruitment_application_history_application_idx on public.recruitment_application_history (application_id, created_at desc);

alter table public.recruitment_application_notes enable row level security;
alter table public.recruitment_application_history enable row level security;

create policy recruitment_application_notes_command_select on public.recruitment_application_notes
for select to authenticated using ((select app_private.current_access_tier()) in ('Executive','Command'));
create policy recruitment_application_history_command_select on public.recruitment_application_history
for select to authenticated using ((select app_private.current_access_tier()) in ('Executive','Command'));

-- The server-side review endpoint is the only writer. This prevents a browser client,
-- including a Command client, from altering decisions or forging history directly.
revoke all on public.recruitment_applications, public.recruitment_application_notes, public.recruitment_application_history from anon, authenticated;
grant usage on schema public to authenticated;
grant select on public.recruitment_applications, public.recruitment_application_notes, public.recruitment_application_history to authenticated;
revoke all on all sequences in schema public from anon, authenticated;

comment on table public.recruitment_application_notes is 'Internal-only, append-only Command notes for recruitment applications.';
comment on table public.recruitment_application_history is 'Append-only Command audit history for recruitment workflow events.';
