create index acting_supervisor_grants_granted_by_idx on public.acting_supervisor_grants (granted_by);
create index acting_supervisor_grants_profile_idx on public.acting_supervisor_grants (profile_id);
create index acting_supervisor_grants_revoked_by_idx on public.acting_supervisor_grants (revoked_by) where revoked_by is not null;
create index audit_log_actor_profile_idx on public.audit_log (actor_profile_id, created_at desc) where actor_profile_id is not null;
create index call_sign_assignments_assigned_by_idx on public.call_sign_assignments (assigned_by) where assigned_by is not null;
create index call_sign_assignments_released_by_idx on public.call_sign_assignments (released_by) where released_by is not null;
create index certifications_approved_by_idx on public.certifications (approved_by) where approved_by is not null;
create index certifications_profile_idx on public.certifications (profile_id, status);
create index certifications_requested_by_idx on public.certifications (requested_by) where requested_by is not null;
create index command_announcements_published_by_idx on public.command_announcements (published_by);
create index division_assignments_assigned_by_idx on public.division_assignments (assigned_by) where assigned_by is not null;
create index division_assignments_profile_idx on public.division_assignments (profile_id, effective_at desc);
create index guardian_records_approved_by_idx on public.guardian_records (approved_by) where approved_by is not null;
create index personnel_profiles_deactivated_by_idx on public.personnel_profiles (deactivated_by) where deactivated_by is not null;
create index personnel_requests_decided_by_idx on public.personnel_requests (decided_by) where decided_by is not null;
create index personnel_requests_requester_idx on public.personnel_requests (requester_profile_id, created_at desc);
create index session_events_profile_idx on public.session_events (profile_id, created_at desc);
create index training_progress_evaluator_idx on public.training_progress (evaluator_profile_id) where evaluator_profile_id is not null;
create index training_progress_profile_idx on public.training_progress (profile_id, created_at desc);
