-- V2 PREVIEW FOUNDATION ONLY
-- This migration is committed for review but is not to be applied to production
-- until the structured authority model and database-side authorization helpers are approved.

create table public.personnel_documents (
  id uuid primary key default gen_random_uuid(),
  document_number bigint generated by default as identity unique,
  profile_id uuid not null references public.personnel_profiles(id) on delete restrict,
  title text not null check (char_length(title) between 2 and 180),
  category text not null check (category in (
    'Personnel Action',
    'Guardian',
    'Training',
    'Certification',
    'Evaluation',
    'Leave',
    'Recognition',
    'Administrative',
    'Other'
  )),
  description text,
  document_date date,
  file_name text not null check (char_length(file_name) between 1 and 240),
  storage_path text not null unique,
  mime_type text not null,
  file_size_bytes bigint not null check (file_size_bytes > 0 and file_size_bytes <= 26214400),
  checksum_sha256 text check (checksum_sha256 is null or checksum_sha256 ~ '^[A-Fa-f0-9]{64}$'),
  visibility text not null default 'Supervisory' check (visibility in ('Personnel','Supervisory','Command','Executive')),
  source_type text not null default 'Manual' check (source_type in (
    'Manual','Guardian','Certification','Training','Leave','Personnel Action','Award','Other'
  )),
  source_table text,
  source_record_id text,
  status text not null default 'Active' check (status in ('Active','Archived','Superseded','Removed')),
  supersedes_document_id uuid references public.personnel_documents(id) on delete restrict,
  uploaded_by uuid not null references public.personnel_profiles(id) on delete restrict,
  archived_at timestamptz,
  archived_by uuid references public.personnel_profiles(id) on delete restrict,
  archive_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check ((status = 'Active' and archived_at is null) or status <> 'Active' or archived_at is not null)
);

create index personnel_documents_profile_idx
  on public.personnel_documents (profile_id, document_date desc, created_at desc);

create index personnel_documents_category_idx
  on public.personnel_documents (profile_id, category, status);

create index personnel_documents_source_idx
  on public.personnel_documents (source_type, source_table, source_record_id)
  where source_record_id is not null;

create trigger personnel_documents_set_updated_at
before update on public.personnel_documents
for each row execute function app_private.set_updated_at();

alter table public.personnel_documents enable row level security;

-- Intentionally no authenticated table policies in this foundation migration.
-- Policies must be added only after database-side V2 authority resolution exists.
-- Service-role operations remain available for controlled migration/administration.

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'personnel-documents',
  'personnel-documents',
  false,
  26214400,
  array[
    'application/pdf',
    'image/jpeg',
    'image/png',
    'image/webp',
    'text/plain',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
  ]::text[]
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

-- Intentionally no storage.objects policies yet.
-- The future policy must authorize by the metadata row's profile_id and the actor's
-- resolved LSCSO authority path, not by rank label or legacy division text alone.
