create table public.recruitment_applications (
  id uuid primary key default gen_random_uuid(),
  application_number bigint generated by default as identity unique,
  status text not null default 'Pending' check (status in ('Pending','Under Review','Interview','Accepted','Denied','Withdrawn','Archived')),

  full_name text not null check (char_length(trim(full_name)) between 2 and 120),
  discord_username text not null check (char_length(trim(discord_username)) between 2 and 100),
  age integer not null check (age between 13 and 100),
  timezone text not null check (char_length(trim(timezone)) between 2 and 80),
  fivem_experience text not null,
  serious_rp_experience text not null,

  weekly_hours text not null,
  upcoming_commitments text not null,
  mandatory_training text not null check (mandatory_training in ('Yes','No')),

  previous_departments text not null,
  previous_ranks text not null,
  supervisory_experience text not null,
  serious_roleplay_definition text not null,
  good_le_roleplayer text not null,

  why_lscso text not null,
  lscso_goals text not null,
  career_path text not null,
  department_expectations text not null,
  contribution text not null,

  reasonable_suspicion_probable_cause text not null,
  officer_discretion text not null,
  use_of_force_factors text not null,
  radio_communication text not null,

  scenario_speeding_nervous text not null,
  scenario_fleeing_vehicle text not null,
  scenario_warrant text not null,
  scenario_deputy_policy_violation text not null,
  scenario_supervisor_order text not null,

  prior_discipline text not null check (prior_discipline in ('Yes','No')),
  prior_discipline_explanation text not null default '',
  breaking_character text not null,
  friend_policy_violation text not null,
  protect_fellow_officer text not null,
  honesty_importance text not null,

  anything_else text not null,
  self_improvement text not null,
  policy_agreement text not null check (policy_agreement = 'Yes'),
  applicant_certification boolean not null default false check (applicant_certification = true),

  reviewer_profile_id uuid references public.personnel_profiles(id),
  review_notes text,
  decision_notes text,
  decided_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index recruitment_applications_status_idx
  on public.recruitment_applications (status, created_at desc);
create index recruitment_applications_created_idx
  on public.recruitment_applications (created_at desc);

create or replace function app_private.set_recruitment_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger recruitment_applications_updated_at
before update on public.recruitment_applications
for each row execute function app_private.set_recruitment_updated_at();

alter table public.recruitment_applications enable row level security;

-- Public applicants may submit applications, but may not read or update them.
create policy recruitment_applications_public_insert
on public.recruitment_applications
for insert to anon, authenticated
with check (
  status = 'Pending'
  and reviewer_profile_id is null
  and review_notes is null
  and decision_notes is null
  and decided_at is null
);

-- Only Executive and Command personnel may review recruitment applications.
create policy recruitment_applications_command_select
on public.recruitment_applications
for select to authenticated
using (
  (select app_private.current_access_tier()) in ('Executive','Command')
);

create policy recruitment_applications_command_update
on public.recruitment_applications
for update to authenticated
using (
  (select app_private.current_access_tier()) in ('Executive','Command')
)
with check (
  (select app_private.current_access_tier()) in ('Executive','Command')
);

-- Prevent ordinary clients from deleting applications.
revoke delete on public.recruitment_applications from anon, authenticated;

comment on table public.recruitment_applications is 'LSCSO public recruitment applications and command review records.';
