create table public.personnel_correspondence (
  id uuid primary key default gen_random_uuid(),
  correspondence_number bigint generated by default as identity unique,
  recipient_profile_id uuid not null references public.personnel_profiles(id) on delete restrict,
  author_profile_id uuid not null references public.personnel_profiles(id) on delete restrict,
  document_type text not null default 'Welcome Letter' check (document_type in ('Welcome Letter','Command Letter','Administrative Notice')),
  subject text not null check (char_length(trim(subject)) between 2 and 140),
  body text not null check (char_length(trim(body)) between 20 and 10000),
  sent_at timestamptz not null default now(),
  archived_at timestamptz,
  created_at timestamptz not null default now()
);

comment on table public.personnel_correspondence is
  'Command-authored letters delivered to a member''s protected My Documents record.';

create index personnel_correspondence_recipient_idx
  on public.personnel_correspondence(recipient_profile_id, sent_at desc)
  where archived_at is null;

create index personnel_correspondence_author_idx
  on public.personnel_correspondence(author_profile_id, sent_at desc);

alter table public.personnel_correspondence enable row level security;

create policy personnel_correspondence_read on public.personnel_correspondence
for select to authenticated using (
  recipient_profile_id = (select app_private.current_profile_id())
  or (select app_private.current_access_tier()) in ('Executive','Command')
);

grant select on public.personnel_correspondence to authenticated;
revoke insert, update, delete on public.personnel_correspondence from authenticated, anon;

create or replace function public.send_personnel_welcome_letter(
  target_profile_id uuid,
  letter_subject text,
  letter_body text
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor uuid := app_private.current_profile_id();
  v_tier text := app_private.current_access_tier();
  v_id uuid;
  v_subject text := trim(coalesce(letter_subject, ''));
  v_body text := trim(coalesce(letter_body, ''));
begin
  if v_actor is null or v_tier not in ('Executive','Command') then
    raise exception 'Command access is required to send personnel letters';
  end if;
  if not exists (
    select 1 from public.personnel_profiles
    where id = target_profile_id and status <> 'Deactivated'
  ) then
    raise exception 'Active personnel record not found';
  end if;
  if char_length(v_subject) not between 2 and 140 then
    raise exception 'Subject must be between 2 and 140 characters';
  end if;
  if char_length(v_body) not between 20 and 10000 then
    raise exception 'Letter must be between 20 and 10,000 characters';
  end if;

  insert into public.personnel_correspondence(
    recipient_profile_id,
    author_profile_id,
    document_type,
    subject,
    body
  ) values (
    target_profile_id,
    v_actor,
    'Welcome Letter',
    v_subject,
    v_body
  ) returning id into v_id;

  insert into public.notifications(
    recipient_profile_id,
    notification_type,
    title,
    message,
    href
  ) values (
    target_profile_id,
    'Personnel Document',
    'Welcome letter received',
    v_subject,
    '/portal/personnel#documents'
  );

  insert into public.audit_log(
    actor_user_id,
    actor_profile_id,
    action,
    table_name,
    record_id,
    new_data
  ) values (
    (select auth.uid()),
    v_actor,
    'SEND_PERSONNEL_WELCOME_LETTER',
    'personnel_correspondence',
    v_id::text,
    jsonb_build_object(
      'recipient_profile_id', target_profile_id,
      'document_type', 'Welcome Letter',
      'subject', v_subject
    )
  );

  return v_id;
end;
$$;

revoke all on function public.send_personnel_welcome_letter(uuid,text,text) from public, anon;
grant execute on function public.send_personnel_welcome_letter(uuid,text,text) to authenticated;

create or replace function public.v2_assign_personnel_to_unit(
  p_profile_id uuid,
  p_unit_id uuid,
  p_assignment_type text,
  p_notes text default null
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor uuid := app_private.current_profile_id();
  v_id uuid;
begin
  if app_private.current_access_tier() not in ('Executive','Command') then
    raise exception 'Command authority required';
  end if;
  if p_assignment_type not in ('Primary','Secondary','Special','Temporary','Training') then raise exception 'Invalid assignment type'; end if;
  if not exists (select 1 from public.personnel_profiles where id = p_profile_id and status <> 'Deactivated') then raise exception 'Personnel not found'; end if;
  if not exists (select 1 from public.organizational_units where id = p_unit_id and active) then raise exception 'Unit not found'; end if;

  if p_assignment_type = 'Primary' then
    update public.personnel_unit_assignments
      set ends_at = now(), ended_by = v_actor, end_reason = 'Replaced by new primary assignment'
      where profile_id = p_profile_id and assignment_type = 'Primary' and ends_at is null;
  end if;

  insert into public.personnel_unit_assignments(profile_id, organizational_unit_id, assignment_type, assigned_by, notes)
  values (p_profile_id, p_unit_id, p_assignment_type, v_actor, nullif(trim(coalesce(p_notes,'')),''))
  returning id into v_id;

  insert into public.audit_log(actor_user_id, actor_profile_id, action, table_name, record_id, new_data)
  values ((select auth.uid()), v_actor, 'V2_ASSIGN_PERSONNEL', 'personnel_unit_assignments', v_id::text,
          jsonb_build_object('profile_id',p_profile_id,'unit_id',p_unit_id,'assignment_type',p_assignment_type,'notes',p_notes));
  return v_id;
end;
$$;

create or replace function public.v2_end_personnel_assignment(
  p_assignment_id uuid,
  p_reason text default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor uuid := app_private.current_profile_id();
  v_old jsonb;
begin
  if app_private.current_access_tier() not in ('Executive','Command') then
    raise exception 'Command authority required';
  end if;
  select to_jsonb(a) into v_old from public.personnel_unit_assignments a where a.id = p_assignment_id and a.ends_at is null;
  if v_old is null then raise exception 'Active assignment not found'; end if;

  update public.personnel_unit_assignments
    set ends_at = now(), ended_by = v_actor, end_reason = nullif(trim(coalesce(p_reason,'')),'')
    where id = p_assignment_id;

  insert into public.audit_log(actor_user_id, actor_profile_id, action, table_name, record_id, old_data, new_data)
  values ((select auth.uid()), v_actor, 'V2_END_PERSONNEL_ASSIGNMENT', 'personnel_unit_assignments', p_assignment_id::text, v_old,
          jsonb_build_object('ends_at',now(),'reason',p_reason));
end;
$$;

revoke all on function public.v2_assign_personnel_to_unit(uuid,uuid,text,text) from public, anon;
revoke all on function public.v2_end_personnel_assignment(uuid,text) from public, anon;
grant execute on function public.v2_assign_personnel_to_unit(uuid,uuid,text,text) to authenticated;
grant execute on function public.v2_end_personnel_assignment(uuid,text) to authenticated;
