
create schema if not exists app_private;
revoke all on schema app_private from public, anon, authenticated;

create table public.personnel_profiles (
  id uuid primary key default gen_random_uuid(),
  auth_user_id uuid unique references auth.users(id) on delete set null,
  personnel_id text not null unique check (personnel_id ~ '^LS-[0-9]{3}$'),
  username text,
  display_name text not null check (char_length(display_name) between 2 and 120),
  greeting_name text not null check (char_length(greeting_name) between 2 and 120),
  rank text not null check (rank in (
    'Sheriff','Undersheriff','Major','Captain','1st Lieutenant','Lieutenant',
    'Sergeant','Corporal','Master Deputy','Deputy III','Deputy II','Deputy','Recruit'
  )),
  access_tier text not null check (access_tier in ('Executive','Command','Supervisor','Preliminary','Deputy')),
  call_sign text check (call_sign is null or call_sign ~ '^S-4[0-9]{2}$'),
  division text not null default 'Unassigned',
  supervisor_label text not null default 'Pending command assignment',
  status text not null default 'Active' check (status in ('Active','Acting','Suspended','Deactivated')),
  is_test_account boolean not null default false,
  credentials_assigned boolean generated always as (auth_user_id is not null) stored,
  last_sign_in_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deactivated_at timestamptz,
  deactivated_by uuid references public.personnel_profiles(id)
);

create unique index personnel_profiles_username_unique
  on public.personnel_profiles (lower(username))
  where username is not null;

create unique index personnel_profiles_active_call_sign_unique
  on public.personnel_profiles (call_sign)
  where call_sign is not null and status <> 'Deactivated';

create table public.call_sign_assignments (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.personnel_profiles(id) on delete restrict,
  call_sign text not null check (call_sign ~ '^S-4[0-9]{2}$'),
  assigned_at timestamptz not null default now(),
  assigned_by uuid references public.personnel_profiles(id),
  released_at timestamptz,
  released_by uuid references public.personnel_profiles(id),
  release_reason text,
  created_at timestamptz not null default now(),
  check (released_at is null or released_at >= assigned_at)
);

create unique index call_sign_assignments_active_unique
  on public.call_sign_assignments (call_sign)
  where released_at is null;

create index call_sign_assignments_profile_idx
  on public.call_sign_assignments (profile_id, assigned_at desc);

create table public.division_assignments (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.personnel_profiles(id) on delete cascade,
  division text not null,
  assignment_type text not null default 'Primary' check (assignment_type in ('Primary','Secondary','Temporary')),
  effective_at timestamptz not null default now(),
  ends_at timestamptz,
  assigned_by uuid references public.personnel_profiles(id),
  notes text,
  created_at timestamptz not null default now(),
  check (ends_at is null or ends_at > effective_at)
);

create table public.certifications (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.personnel_profiles(id) on delete cascade,
  name text not null,
  issuer text not null,
  certificate_number text,
  status text not null default 'Current' check (status in ('Requested','Pending','Current','Expired','Revoked','Denied')),
  issued_on date,
  expires_on date,
  requested_by uuid references public.personnel_profiles(id),
  approved_by uuid references public.personnel_profiles(id),
  approved_at timestamptz,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (expires_on is null or issued_on is null or expires_on >= issued_on)
);

create table public.guardian_records (
  id uuid primary key default gen_random_uuid(),
  guardian_number bigint generated by default as identity unique,
  subject_profile_id uuid not null references public.personnel_profiles(id) on delete restrict,
  author_profile_id uuid not null references public.personnel_profiles(id) on delete restrict,
  approved_by uuid references public.personnel_profiles(id),
  record_type text not null check (record_type in ('Feedback','Written Warning','Write-Up','Commendation')),
  status text not null default 'Draft' check (status in (
    'Draft','Pending Approval','Approved','Denied','Issued','Awaiting Acknowledgment',
    'Acknowledged','Follow-Up Due','Closed'
  )),
  title text not null check (char_length(title) between 3 and 180),
  incident_at timestamptz not null,
  location text,
  policy_reference text,
  observed_behavior text,
  expected_standard text,
  action_taken text,
  follow_up_plan text,
  follow_up_due_at timestamptz,
  command_notes text,
  structured_fields jsonb not null default '{}'::jsonb,
  employee_response text,
  submitted_at timestamptz,
  approved_at timestamptz,
  issued_at timestamptz,
  acknowledged_at timestamptz,
  closed_at timestamptz,
  is_test_record boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index guardian_records_subject_idx
  on public.guardian_records (subject_profile_id, created_at desc);
create index guardian_records_status_idx
  on public.guardian_records (status, follow_up_due_at);
create index guardian_records_author_idx
  on public.guardian_records (author_profile_id, created_at desc);

create table public.personnel_requests (
  id uuid primary key default gen_random_uuid(),
  request_number bigint generated by default as identity unique,
  requester_profile_id uuid not null references public.personnel_profiles(id) on delete cascade,
  request_type text not null check (request_type in ('Promotion','Division Transfer','Certification','Acting Supervisor','Other')),
  status text not null default 'Submitted' check (status in ('Draft','Submitted','In Review','Approved','Denied','Cancelled','Completed')),
  subject text not null,
  details text not null,
  requested_effective_at timestamptz,
  decided_by uuid references public.personnel_profiles(id),
  decision_notes text,
  decided_at timestamptz,
  is_test_record boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.acting_supervisor_grants (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.personnel_profiles(id) on delete cascade,
  granted_by uuid not null references public.personnel_profiles(id),
  starts_at timestamptz not null default now(),
  expires_at timestamptz not null,
  scope text not null,
  revoked_at timestamptz,
  revoked_by uuid references public.personnel_profiles(id),
  created_at timestamptz not null default now(),
  check (expires_at > starts_at)
);

create table public.training_progress (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.personnel_profiles(id) on delete cascade,
  program_type text not null check (program_type in ('Academy','FTO','Remedial','Continuing Education')),
  phase text not null,
  status text not null default 'Not Started' check (status in ('Not Started','In Progress','Needs Improvement','Complete','Released','Withdrawn')),
  evaluator_profile_id uuid references public.personnel_profiles(id),
  progress_percent integer not null default 0 check (progress_percent between 0 and 100),
  started_on date,
  completed_on date,
  evaluation_notes text,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table public.command_announcements (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  body text not null,
  priority text not null default 'Routine' check (priority in ('Routine','Important','Urgent')),
  published_by uuid not null references public.personnel_profiles(id),
  published_at timestamptz not null default now(),
  expires_at timestamptz,
  requires_acknowledgment boolean not null default false,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.notifications (
  id uuid primary key default gen_random_uuid(),
  recipient_profile_id uuid not null references public.personnel_profiles(id) on delete cascade,
  notification_type text not null,
  title text not null,
  message text not null,
  href text,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create index notifications_recipient_idx
  on public.notifications (recipient_profile_id, read_at, created_at desc);

create table public.session_events (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.personnel_profiles(id) on delete cascade,
  event_type text not null check (event_type in ('Sign In','Sign Out','Password Changed','Forced Logout','Session Revoked')),
  ip_address inet,
  user_agent text,
  created_at timestamptz not null default now()
);

create table public.audit_log (
  id bigint generated by default as identity primary key,
  actor_user_id uuid,
  actor_profile_id uuid references public.personnel_profiles(id),
  action text not null,
  table_name text not null,
  record_id text,
  old_data jsonb,
  new_data jsonb,
  created_at timestamptz not null default now()
);

create or replace function app_private.current_profile_id()
returns uuid
language sql
stable
security definer
set search_path = ''
as $$
  select p.id
  from public.personnel_profiles p
  where p.auth_user_id = (select auth.uid())
    and p.status in ('Active','Acting')
  limit 1
$$;

create or replace function app_private.current_access_tier()
returns text
language sql
stable
security definer
set search_path = ''
as $$
  select p.access_tier
  from public.personnel_profiles p
  where p.auth_user_id = (select auth.uid())
    and p.status in ('Active','Acting')
  limit 1
$$;

create or replace function app_private.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function app_private.write_audit_log()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor_profile uuid;
  row_id text;
begin
  select p.id into actor_profile
  from public.personnel_profiles p
  where p.auth_user_id = (select auth.uid())
  limit 1;

  row_id := coalesce((case when tg_op = 'DELETE' then to_jsonb(old) else to_jsonb(new) end)->>'id', null);

  insert into public.audit_log (
    actor_user_id,
    actor_profile_id,
    action,
    table_name,
    record_id,
    old_data,
    new_data
  ) values (
    (select auth.uid()),
    actor_profile,
    tg_op,
    tg_table_schema || '.' || tg_table_name,
    row_id,
    case when tg_op in ('UPDATE','DELETE') then to_jsonb(old) else null end,
    case when tg_op in ('INSERT','UPDATE') then to_jsonb(new) else null end
  );

  return case when tg_op = 'DELETE' then old else new end;
end;
$$;

create trigger personnel_profiles_updated_at
before update on public.personnel_profiles
for each row execute function app_private.set_updated_at();
create trigger certifications_updated_at
before update on public.certifications
for each row execute function app_private.set_updated_at();
create trigger guardians_updated_at
before update on public.guardian_records
for each row execute function app_private.set_updated_at();
create trigger requests_updated_at
before update on public.personnel_requests
for each row execute function app_private.set_updated_at();
create trigger training_updated_at
before update on public.training_progress
for each row execute function app_private.set_updated_at();

-- Production personnel identities are provisioned through the secured personnel-admin workflow.
-- Authentication user IDs are intentionally not hardcoded in migrations.

alter table public.personnel_profiles enable row level security;
alter table public.call_sign_assignments enable row level security;
alter table public.division_assignments enable row level security;
alter table public.certifications enable row level security;
alter table public.guardian_records enable row level security;
alter table public.personnel_requests enable row level security;
alter table public.acting_supervisor_grants enable row level security;
alter table public.training_progress enable row level security;
alter table public.command_announcements enable row level security;
alter table public.notifications enable row level security;
alter table public.session_events enable row level security;
alter table public.audit_log enable row level security;

create policy personnel_profiles_select on public.personnel_profiles
for select to authenticated
using (
  auth_user_id = (select auth.uid())
  or (select app_private.current_access_tier()) in ('Executive','Command','Supervisor','Preliminary')
);

create policy call_sign_assignments_select on public.call_sign_assignments
for select to authenticated
using (
  profile_id = (select app_private.current_profile_id())
  or (select app_private.current_access_tier()) in ('Executive','Command','Supervisor','Preliminary')
);

create policy division_assignments_select on public.division_assignments
for select to authenticated
using (
  profile_id = (select app_private.current_profile_id())
  or (select app_private.current_access_tier()) in ('Executive','Command','Supervisor')
);

create policy certifications_select on public.certifications
for select to authenticated
using (
  profile_id = (select app_private.current_profile_id())
  or (select app_private.current_access_tier()) in ('Executive','Command','Supervisor')
);

create policy guardian_records_select on public.guardian_records
for select to authenticated
using (
  subject_profile_id = (select app_private.current_profile_id())
  or author_profile_id = (select app_private.current_profile_id())
  or (select app_private.current_access_tier()) in ('Executive','Command')
);

create policy guardian_records_insert on public.guardian_records
for insert to authenticated
with check (
  author_profile_id = (select app_private.current_profile_id())
  and (select app_private.current_access_tier()) in ('Executive','Command','Supervisor','Preliminary')
);

create policy guardian_records_update on public.guardian_records
for update to authenticated
using (
  (author_profile_id = (select app_private.current_profile_id()) and status in ('Draft','Pending Approval'))
  or (select app_private.current_access_tier()) in ('Executive','Command')
)
with check (
  (author_profile_id = (select app_private.current_profile_id()) and status in ('Draft','Pending Approval'))
  or (select app_private.current_access_tier()) in ('Executive','Command')
);

create policy personnel_requests_select on public.personnel_requests
for select to authenticated
using (
  requester_profile_id = (select app_private.current_profile_id())
  or (select app_private.current_access_tier()) in ('Executive','Command')
);

create policy personnel_requests_insert on public.personnel_requests
for insert to authenticated
with check (requester_profile_id = (select app_private.current_profile_id()));

create policy personnel_requests_update on public.personnel_requests
for update to authenticated
using (
  (requester_profile_id = (select app_private.current_profile_id()) and status in ('Draft','Submitted'))
  or (select app_private.current_access_tier()) in ('Executive','Command')
)
with check (
  requester_profile_id = (select app_private.current_profile_id())
  or (select app_private.current_access_tier()) in ('Executive','Command')
);

create policy acting_supervisor_grants_select on public.acting_supervisor_grants
for select to authenticated
using (
  profile_id = (select app_private.current_profile_id())
  or (select app_private.current_access_tier()) in ('Executive','Command','Supervisor')
);

create policy training_progress_select on public.training_progress
for select to authenticated
using (
  profile_id = (select app_private.current_profile_id())
  or (select app_private.current_access_tier()) in ('Executive','Command','Supervisor')
);

create policy command_announcements_select on public.command_announcements
for select to authenticated
using (active and (expires_at is null or expires_at > now()));

create policy notifications_select on public.notifications
for select to authenticated
using (recipient_profile_id = (select app_private.current_profile_id()));

create policy notifications_update on public.notifications
for update to authenticated
using (recipient_profile_id = (select app_private.current_profile_id()))
with check (recipient_profile_id = (select app_private.current_profile_id()));

create policy session_events_select on public.session_events
for select to authenticated
using (
  profile_id = (select app_private.current_profile_id())
  or (select app_private.current_access_tier()) = 'Executive'
);

create policy audit_log_select on public.audit_log
for select to authenticated
using ((select app_private.current_access_tier()) in ('Executive','Command'));

revoke all on all tables in schema public from anon;
grant usage on schema public to authenticated;
grant select on all tables in schema public to authenticated;
grant insert, update on public.guardian_records to authenticated;
grant insert, update on public.personnel_requests to authenticated;
grant update on public.notifications to authenticated;
grant usage, select on all sequences in schema public to authenticated;

revoke all on function app_private.current_profile_id() from public;
revoke all on function app_private.current_access_tier() from public;
grant execute on function app_private.current_profile_id() to authenticated;
grant execute on function app_private.current_access_tier() to authenticated;

create or replace function public.acknowledge_guardian(record_id uuid, response_text text default null)
returns public.guardian_records
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_profile uuid;
  updated_record public.guardian_records;
begin
  current_profile := app_private.current_profile_id();
  if current_profile is null then
    raise exception 'Authorized profile required';
  end if;

  update public.guardian_records
  set
    status = 'Acknowledged',
    acknowledged_at = now(),
    employee_response = nullif(trim(response_text), ''),
    updated_at = now()
  where id = record_id
    and subject_profile_id = current_profile
    and status in ('Issued','Awaiting Acknowledgment')
  returning * into updated_record;

  if updated_record.id is null then
    raise exception 'Guardian record is unavailable for acknowledgment';
  end if;

  return updated_record;
end;
$$;

revoke all on function public.acknowledge_guardian(uuid, text) from public, anon;
grant execute on function public.acknowledge_guardian(uuid, text) to authenticated;

create trigger personnel_profiles_audit
after insert or update or delete on public.personnel_profiles
for each row execute function app_private.write_audit_log();
create trigger call_sign_assignments_audit
after insert or update or delete on public.call_sign_assignments
for each row execute function app_private.write_audit_log();
create trigger certifications_audit
after insert or update or delete on public.certifications
for each row execute function app_private.write_audit_log();
create trigger guardian_records_audit
after insert or update or delete on public.guardian_records
for each row execute function app_private.write_audit_log();
create trigger personnel_requests_audit
after insert or update or delete on public.personnel_requests
for each row execute function app_private.write_audit_log();
create trigger acting_supervisor_grants_audit
after insert or update or delete on public.acting_supervisor_grants
for each row execute function app_private.write_audit_log();
create trigger training_progress_audit
after insert or update or delete on public.training_progress
for each row execute function app_private.write_audit_log();
create trigger command_announcements_audit
after insert or update or delete on public.command_announcements
for each row execute function app_private.write_audit_log();
