create table public.lscso_mail_groups (
  id uuid primary key default gen_random_uuid(),
  address text not null unique check (address = lower(address) and address ~ '^[a-z0-9][a-z0-9._-]{1,62}@lscso\.gov$' and address <> 'noreply@lscso.gov'),
  display_name text not null check (char_length(trim(display_name)) between 2 and 120),
  description text,
  group_type text not null default 'distribution' check (group_type in ('distribution','shared')),
  send_policy text not null default 'any_lscso' check (send_policy in ('any_lscso','members','managers')),
  active boolean not null default true,
  created_by uuid references public.personnel_profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.lscso_mail_group_members (
  id uuid primary key default gen_random_uuid(),
  group_id uuid not null references public.lscso_mail_groups(id) on delete cascade,
  profile_id uuid not null references public.personnel_profiles(id) on delete cascade,
  role text not null default 'member' check (role in ('member','manager')),
  added_by uuid references public.personnel_profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  unique (group_id, profile_id)
);

create table public.lscso_mail_messages (
  id uuid primary key default gen_random_uuid(),
  sender_profile_id uuid references public.personnel_profiles(id) on delete set null,
  sender_address text not null check (sender_address = lower(sender_address) and sender_address ~ '^[a-z0-9][a-z0-9._-]{1,62}@lscso\.gov$'),
  sender_name text not null check (char_length(trim(sender_name)) between 2 and 160),
  subject text not null check (char_length(trim(subject)) between 1 and 200),
  body text not null check (char_length(body) between 1 and 20000),
  system_message boolean not null default false,
  reply_to_message_id uuid references public.lscso_mail_messages(id) on delete set null,
  metadata jsonb not null default '{}'::jsonb,
  sent_at timestamptz not null default now()
);

create table public.lscso_mail_deliveries (
  id uuid primary key default gen_random_uuid(),
  message_id uuid not null references public.lscso_mail_messages(id) on delete cascade,
  recipient_profile_id uuid not null references public.personnel_profiles(id) on delete cascade,
  recipient_address text not null check (recipient_address = lower(recipient_address) and recipient_address ~ '^[a-z0-9][a-z0-9._-]{1,62}@lscso\.gov$'),
  delivery_type text not null default 'to' check (delivery_type in ('to','cc','bcc','group')),
  delivered_via text,
  folder text not null default 'inbox' check (folder in ('inbox','archive','trash')),
  is_read boolean not null default false,
  read_at timestamptz,
  created_at timestamptz not null default now(),
  unique (message_id, recipient_profile_id)
);

create table public.lscso_mail_audit (
  id bigint generated by default as identity primary key,
  actor_profile_id uuid references public.personnel_profiles(id) on delete set null,
  event_type text not null,
  target_address text,
  message_id uuid references public.lscso_mail_messages(id) on delete set null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index lscso_mail_groups_active_idx on public.lscso_mail_groups(active, address);
create index lscso_mail_group_members_profile_idx on public.lscso_mail_group_members(profile_id, group_id);
create index lscso_mail_messages_sender_idx on public.lscso_mail_messages(sender_profile_id, sent_at desc);
create index lscso_mail_messages_sent_idx on public.lscso_mail_messages(sent_at desc);
create index lscso_mail_deliveries_recipient_idx on public.lscso_mail_deliveries(recipient_profile_id, folder, created_at desc);
create index lscso_mail_deliveries_unread_idx on public.lscso_mail_deliveries(recipient_profile_id, is_read) where folder = 'inbox';
create index lscso_mail_audit_created_idx on public.lscso_mail_audit(created_at desc);

alter table public.lscso_mail_groups enable row level security;
alter table public.lscso_mail_group_members enable row level security;
alter table public.lscso_mail_messages enable row level security;
alter table public.lscso_mail_deliveries enable row level security;
alter table public.lscso_mail_audit enable row level security;

comment on table public.lscso_mail_groups is 'LSCSO internal @lscso.gov distribution lists and shared mailbox identities.';
comment on table public.lscso_mail_messages is 'Canonical LSCSO internal mail messages. System automation uses noreply@lscso.gov.';
comment on table public.lscso_mail_deliveries is 'Per-person LSCSO mailbox deliveries and read/folder state.';
comment on table public.lscso_mail_audit is 'Append-only operational audit trail for LSCSO mail administration and delivery automation.';
